// aot.rs - hone build --exe -c 的 AOT 编译：脚本 → C 中间文件 → 原生可执行文件
// 架构：
//   1. RUNTIME_C：内嵌的 C 运行时（boxed 值模型 HnValue + 引用计数 + 异常 setjmp/longjmp + 核心内置）
//   2. generate()：把 Hone AST 翻译成调用该运行时的 C 代码（含 main()）
//   3. 编译：find_cc() 定位 gcc/clang/cc，-Os -ffunction-sections + 链接期死代码消除 → 几十 KB 级体积
// 值语义与解释器一致：int/float/bool 内嵌；str/list/dict 引用计数（变量读取深拷贝，保持拷贝语义）；
//   函数按值传参；lambda 按值捕获；列表索引赋值克隆写回。
// 约定：所有 hn_* 构造函数返回"拥有"值（引用已计），调用方负责 hn_release_v；
//       表达式求值结果均为拥有值；变量读取返回 hn_copy（深拷贝）。

use std::collections::{HashMap, HashSet};

use crate::ast::*;
use crate::error::codes;
use crate::error::ZError;
use crate::lexer::Span;

/// 内嵌 C 运行时（值模型 / 内存管理 / 运算 / 集合 / 闭包 / 异常 / 核心内置）。
const RUNTIME_C: &str = r##"/* Hone AOT runtime (auto-generated by hone build --exe -c) */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>
#include <time.h>
#ifdef _WIN32
#include <windows.h>
#endif

typedef struct HnValue HnValue;
typedef struct HnStr HnStr;
typedef struct HnList HnList;
typedef struct HnDict HnDict;
typedef struct HnFn HnFn;
typedef struct HnErr HnErr;
typedef HnValue (*HnFnPtr)(HnValue* args, int nargs, HnValue* cap, int ncap);

enum { HN_INT, HN_FLOAT, HN_BOOL, HN_STR, HN_LIST, HN_DICT, HN_NULL, HN_ERR, HN_FN };

struct HnStr { int refs; int len; char* data; };
struct HnList { int refs; int len; int cap; HnValue* items; };
struct HnDict { int refs; int len; int cap; char** keys; HnValue* vals; };
struct HnFn { int refs; HnFnPtr ptr; HnValue* cap; int ncap; };
struct HnErr { int refs; int code; char* msg; char* file; int line; int col; char* context; };

struct HnValue {
    int type;
    union {
        int64_t i;
        double f;
        bool b;
        HnStr* s;
        HnList* list;
        HnDict* dict;
        HnFn* fn;
        HnErr* err;
    } as;
};

/* ---------- 异常（setjmp/longjmp + 全局错误） ---------- */
static jmp_buf* hn_jmp_top = NULL;
static HnValue hn_err_val;

static void hn_throw_value(HnValue v) {
    hn_err_val = v;
    if (hn_jmp_top) longjmp(*hn_jmp_top, 1);
    /* 无捕获：打印并退出 */
    fprintf(stderr, "uncaught error: ");
    if (v.type == HN_ERR) {
        fprintf(stderr, "H%d %s", v.as.err->code, v.as.err->msg);
        if (v.as.err->file) fprintf(stderr, " at %s:%d", v.as.err->file, v.as.err->line);
    } else if (v.type == HN_STR) {
        fprintf(stderr, "%s", v.as.s->data);
    } else {
        fputs("(non-error value)", stderr);
    }
    fputc('\n', stderr);
    exit(1);
}

/* ---------- 内存管理 ---------- */
static HnValue hn_retain_v(HnValue v) {
    switch (v.type) {
        case HN_STR: v.as.s->refs++; break;
        case HN_LIST: v.as.list->refs++; break;
        case HN_DICT: v.as.dict->refs++; break;
        case HN_FN: v.as.fn->refs++; break;
        case HN_ERR: v.as.err->refs++; break;
        default: break;
    }
    return v;
}

static void hn_free_value(HnValue v) {
    switch (v.type) {
        case HN_STR: {
            HnStr* s = v.as.s;
            if (--s->refs == 0) { free(s->data); free(s); }
            break;
        }
        case HN_LIST: {
            HnList* l = v.as.list;
            if (--l->refs == 0) {
                for (int i = 0; i < l->len; i++) hn_free_value(l->items[i]);
                free(l->items); free(l);
            }
            break;
        }
        case HN_DICT: {
            HnDict* d = v.as.dict;
            if (--d->refs == 0) {
                for (int i = 0; i < d->len; i++) { free(d->keys[i]); hn_free_value(d->vals[i]); }
                free(d->keys); free(d->vals); free(d);
            }
            break;
        }
        case HN_FN: {
            HnFn* f = v.as.fn;
            if (--f->refs == 0) {
                for (int i = 0; i < f->ncap; i++) hn_free_value(f->cap[i]);
                free(f->cap); free(f);
            }
            break;
        }
        case HN_ERR: {
            HnErr* e = v.as.err;
            if (--e->refs == 0) { free(e->msg); free(e->file); free(e->context); free(e); }
            break;
        }
        default: break;
    }
}

static HnValue hn_int(int64_t i) { HnValue v; v.type = HN_INT; v.as.i = i; return v; }
static HnValue hn_float(double f) { HnValue v; v.type = HN_FLOAT; v.as.f = f; return v; }
static HnValue hn_bool(bool b) { HnValue v; v.type = HN_BOOL; v.as.b = b; return v; }
static HnValue hn_null(void) { HnValue v; v.type = HN_NULL; v.as.i = 0; return v; }

static HnValue hn_str(const char* s) {
    HnValue v; v.type = HN_STR;
    HnStr* o = (HnStr*)malloc(sizeof(HnStr));
    o->len = (int)strlen(s);
    o->data = (char*)malloc((size_t)o->len + 1);
    memcpy(o->data, s, (size_t)o->len + 1);
    o->refs = 1;
    v.as.s = o;
    return v;
}

static HnValue hn_str_len(const char* s, int len) {
    HnValue v; v.type = HN_STR;
    HnStr* o = (HnStr*)malloc(sizeof(HnStr));
    o->len = len;
    o->data = (char*)malloc((size_t)len + 1);
    memcpy(o->data, s, (size_t)len);
    o->data[len] = '\0';
    o->refs = 1;
    v.as.s = o;
    return v;
}

static HnValue hn_list_new(void) {
    HnValue v; v.type = HN_LIST;
    HnList* l = (HnList*)malloc(sizeof(HnList));
    l->refs = 1; l->len = 0; l->cap = 4;
    l->items = (HnValue*)malloc(4 * sizeof(HnValue));
    v.as.list = l;
    return v;
}

static HnValue hn_dict_new(void) {
    HnValue v; v.type = HN_DICT;
    HnDict* d = (HnDict*)malloc(sizeof(HnDict));
    d->refs = 1; d->len = 0; d->cap = 4;
    d->keys = (char**)malloc(4 * sizeof(char*));
    d->vals = (HnValue*)malloc(4 * sizeof(HnValue));
    v.as.dict = d;
    return v;
}

static void hn_list_push(HnValue v, HnValue item) {
    HnList* l = v.as.list;
    if (l->len == l->cap) {
        l->cap *= 2;
        l->items = (HnValue*)realloc(l->items, (size_t)l->cap * sizeof(HnValue));
    }
    l->items[l->len++] = item;
}

static void hn_dict_set(HnValue v, const char* key, HnValue val); /* 前向声明（hn_copy 先于定义使用） */

static HnValue hn_err_new(int code, const char* msg) {
    HnValue v; v.type = HN_ERR;
    HnErr* e = (HnErr*)malloc(sizeof(HnErr));
    e->refs = 1; e->code = code;
    e->msg = (char*)malloc(strlen(msg) + 1);
    strcpy(e->msg, msg);
    e->file = NULL; e->line = 0; e->col = 0; e->context = NULL;
    v.as.err = e;
    return v;
}

/* ---------- 深拷贝（变量读取/传参，保持列表/字典拷贝语义） ---------- */
static HnValue hn_copy(HnValue v) {
    switch (v.type) {
        case HN_INT: return hn_int(v.as.i);
        case HN_FLOAT: return hn_float(v.as.f);
        case HN_BOOL: return hn_bool(v.as.b);
        case HN_NULL: return hn_null();
        case HN_STR: return hn_str_len(v.as.s->data, v.as.s->len);
        case HN_LIST: {
            HnValue n = hn_list_new();
            HnList* l = v.as.list;
            for (int i = 0; i < l->len; i++) hn_list_push(n, hn_copy(l->items[i]));
            return n;
        }
        case HN_DICT: {
            HnValue n = hn_dict_new();
            HnDict* d = v.as.dict;
            for (int i = 0; i < d->len; i++) {
                hn_dict_set(n, d->keys[i], hn_copy(d->vals[i]));
            }
            return n;
        }
        case HN_FN: {
            HnValue n; n.type = HN_FN;
            HnFn* f = (HnFn*)malloc(sizeof(HnFn));
            f->refs = 1; f->ptr = v.as.fn->ptr;
            f->ncap = v.as.fn->ncap;
            f->cap = (HnValue*)malloc((size_t)(f->ncap ? f->ncap : 1) * sizeof(HnValue));
            for (int i = 0; i < f->ncap; i++) f->cap[i] = hn_copy(v.as.fn->cap[i]);
            n.as.fn = f;
            return n;
        }
        case HN_ERR: {
            HnValue n; n.type = HN_ERR;
            HnErr* e = (HnErr*)malloc(sizeof(HnErr));
            *e = *v.as.err;
            e->refs = 1;
            e->msg = (char*)malloc(strlen(v.as.err->msg) + 1);
            strcpy(e->msg, v.as.err->msg);
            if (v.as.err->file) { e->file = (char*)malloc(strlen(v.as.err->file) + 1); strcpy(e->file, v.as.err->file); }
            if (v.as.err->context) { e->context = (char*)malloc(strlen(v.as.err->context) + 1); strcpy(e->context, v.as.err->context); }
            n.as.err = e;
            return n;
        }
    }
    return v;
}

/* ---------- 类型与显示 ---------- */
static const char* hn_type_name(HnValue v) {
    switch (v.type) {
        case HN_INT: return "int";
        case HN_FLOAT: return "float";
        case HN_BOOL: return "bool";
        case HN_STR: return "str";
        case HN_LIST: return "list";
        case HN_DICT: return "dict";
        case HN_NULL: return "null";
        case HN_ERR: return "error";
        case HN_FN: return "fn";
    }
    return "?";
}

/* 生成 display 文本（结果需 free），str 不加引号 */
static char* hn_display(HnValue v) {
    char buf[256];
    switch (v.type) {
        case HN_INT:
            snprintf(buf, sizeof buf, "%lld", (long long)v.as.i);
            return strdup(buf);
        case HN_FLOAT: {
            snprintf(buf, sizeof buf, "%.15g", v.as.f);
            return strdup(buf);
        }
        case HN_BOOL:
            return strdup(v.as.b ? "true" : "false");
        case HN_STR:
            return strdup(v.as.s->data);
        case HN_NULL:
            return strdup("null");
        case HN_LIST: {
            HnList* l = v.as.list;
            size_t total = 2;
            for (int i = 0; i < l->len; i++) { char* s = hn_display(l->items[i]); total += strlen(s) + 3; free(s); }
            char* out = (char*)malloc(total);
            size_t p = 0;
            out[p++] = '[';
            for (int i = 0; i < l->len; i++) {
                if (i) { out[p++] = ','; out[p++] = ' '; }
                char* s = hn_display(l->items[i]);
                size_t n = strlen(s);
                memcpy(out + p, s, n); p += n;
                free(s);
            }
            out[p++] = ']';
            out[p] = '\0';
            return out;
        }
        case HN_DICT: {
            HnDict* d = v.as.dict;
            size_t total = 2;
            for (int i = 0; i < d->len; i++) { char* s = hn_display(d->vals[i]); total += strlen(d->keys[i]) + strlen(s) + 5; free(s); }
            char* out = (char*)malloc(total);
            size_t p = 0;
            out[p++] = '{';
            for (int i = 0; i < d->len; i++) {
                if (i) { out[p++] = ','; out[p++] = ' '; }
                size_t n = strlen(d->keys[i]);
                memcpy(out + p, d->keys[i], n); p += n;
                out[p++] = ':';
                out[p++] = ' ';
                char* s = hn_display(d->vals[i]);
                n = strlen(s);
                memcpy(out + p, s, n); p += n;
                free(s);
            }
            out[p++] = '}';
            out[p] = '\0';
            return out;
        }
        case HN_ERR: {
            snprintf(buf, sizeof buf, "error[H%d]: %s", v.as.err->code, v.as.err->msg);
            return strdup(buf);
        }
        case HN_FN: {
            snprintf(buf, sizeof buf, "fn(%d)", v.as.fn->ncap);
            return strdup(buf);
        }
    }
    return strdup("?");
}

/* ---------- 集合操作 ---------- */
static int hn_dict_find(HnDict* d, const char* key) {
    for (int i = 0; i < d->len; i++) {
        if (strcmp(d->keys[i], key) == 0) return i;
    }
    return -1;
}

static void hn_dict_set(HnValue v, const char* key, HnValue val) {
    HnDict* d = v.as.dict;
    int idx = hn_dict_find(d, key);
    if (idx >= 0) {
        hn_free_value(d->vals[idx]);
        d->vals[idx] = val;
        return;
    }
    if (d->len == d->cap) {
        d->cap *= 2;
        d->keys = (char**)realloc(d->keys, (size_t)d->cap * sizeof(char*));
        d->vals = (HnValue*)realloc(d->vals, (size_t)d->cap * sizeof(HnValue));
    }
    d->keys[d->len] = strdup(key);
    d->vals[d->len] = val;
    d->len++;
}

static HnValue* hn_dict_getp(HnValue v, const char* key) {
    int idx = hn_dict_find(v.as.dict, key);
    return idx >= 0 ? &v.as.dict->vals[idx] : NULL;
}

/* 按值设键（字典推导式用）：key 为 str 值；key/val 所有权转移给 dict */
static void hn_dict_set_v(HnValue v, HnValue key, HnValue val) {
    if (key.type != HN_STR) {
        hn_free_value(key); hn_free_value(val);
        hn_throw_value(hn_err_new(1, "dict key must be a str"));
        return;
    }
    hn_dict_set(v, key.as.s->data, val);
    hn_free_value(key);
}

/* ---------- 运算（与解释器语义一致，类型不匹配抛 H004） ---------- */
static HnValue hn_type_err(const char* what) {
    char buf[256];
    snprintf(buf, sizeof buf, "type mismatch: %s", what);
    hn_throw_value(hn_err_new(1, buf));
    return hn_null(); /* 不可达（已 longjmp） */
}

static HnValue hn_add_v(HnValue a, HnValue b) {
    HnValue r;
    if (a.type == HN_INT && b.type == HN_INT) r = hn_int(a.as.i + b.as.i);
    else if (a.type == HN_INT && b.type == HN_FLOAT) r = hn_float((double)a.as.i + b.as.f);
    else if (a.type == HN_FLOAT && b.type == HN_INT) r = hn_float(a.as.f + (double)b.as.i);
    else if (a.type == HN_FLOAT && b.type == HN_FLOAT) r = hn_float(a.as.f + b.as.f);
    else if (a.type == HN_STR && b.type == HN_STR) {
        int n = a.as.s->len + b.as.s->len;
        char* tmp = (char*)malloc((size_t)n + 1);
        memcpy(tmp, a.as.s->data, (size_t)a.as.s->len);
        memcpy(tmp + a.as.s->len, b.as.s->data, (size_t)b.as.s->len);
        tmp[n] = '\0';
        r = hn_str_len(tmp, n);
        free(tmp);
    } else {
        hn_free_value(a); hn_free_value(b);
        return hn_type_err("cannot apply `+` to operands");
    }
    hn_free_value(a); hn_free_value(b);
    return r;
}

static HnValue hn_sub_v(HnValue a, HnValue b) {
    HnValue r;
    if (a.type == HN_INT && b.type == HN_INT) r = hn_int(a.as.i - b.as.i);
    else if (a.type == HN_INT && b.type == HN_FLOAT) r = hn_float((double)a.as.i - b.as.f);
    else if (a.type == HN_FLOAT && b.type == HN_INT) r = hn_float(a.as.f - (double)b.as.i);
    else if (a.type == HN_FLOAT && b.type == HN_FLOAT) r = hn_float(a.as.f - b.as.f);
    else { hn_free_value(a); hn_free_value(b); return hn_type_err("cannot apply `-` to operands"); }
    hn_free_value(a); hn_free_value(b);
    return r;
}

static HnValue hn_mul_v(HnValue a, HnValue b) {
    HnValue r;
    if (a.type == HN_INT && b.type == HN_INT) r = hn_int(a.as.i * b.as.i);
    else if (a.type == HN_INT && b.type == HN_FLOAT) r = hn_float((double)a.as.i * b.as.f);
    else if (a.type == HN_FLOAT && b.type == HN_INT) r = hn_float(a.as.f * (double)b.as.i);
    else if (a.type == HN_FLOAT && b.type == HN_FLOAT) r = hn_float(a.as.f * b.as.f);
    else { hn_free_value(a); hn_free_value(b); return hn_type_err("cannot apply `*` to operands"); }
    hn_free_value(a); hn_free_value(b);
    return r;
}

static HnValue hn_div_v(HnValue a, HnValue b) {
    HnValue r;
    if (a.type == HN_INT && b.type == HN_INT) {
        if (b.as.i == 0) { hn_free_value(a); hn_free_value(b); hn_throw_value(hn_err_new(9, "division by zero")); return hn_null(); }
        r = hn_int(a.as.i / b.as.i);
    } else if (a.type == HN_INT && b.type == HN_FLOAT) {
        r = hn_float((double)a.as.i / b.as.f);
    } else if (a.type == HN_FLOAT && b.type == HN_INT) {
        if (b.as.i == 0) { hn_free_value(a); hn_free_value(b); hn_throw_value(hn_err_new(9, "division by zero")); return hn_null(); }
        r = hn_float(a.as.f / (double)b.as.i);
    } else if (a.type == HN_FLOAT && b.type == HN_FLOAT) {
        if (b.as.f == 0.0) { hn_free_value(a); hn_free_value(b); hn_throw_value(hn_err_new(9, "division by zero")); return hn_null(); }
        r = hn_float(a.as.f / b.as.f);
    } else { hn_free_value(a); hn_free_value(b); return hn_type_err("cannot apply `/` to operands"); }
    hn_free_value(a); hn_free_value(b);
    return r;
}

static HnValue hn_mod_v(HnValue a, HnValue b) {
    HnValue r;
    if (a.type == HN_INT && b.type == HN_INT) {
        if (b.as.i == 0) { hn_free_value(a); hn_free_value(b); hn_throw_value(hn_err_new(9, "modulo by zero")); return hn_null(); }
        r = hn_int(a.as.i % b.as.i);
    } else { hn_free_value(a); hn_free_value(b); return hn_type_err("cannot apply `%` to operands"); }
    hn_free_value(a); hn_free_value(b);
    return r;
}

static HnValue hn_neg_v(HnValue a) {
    HnValue r;
    if (a.type == HN_INT) r = hn_int(-a.as.i);
    else if (a.type == HN_FLOAT) r = hn_float(-a.as.f);
    else { hn_free_value(a); return hn_type_err("unary `-` requires a number"); }
    hn_free_value(a);
    return r;
}

static HnValue hn_not_v(HnValue a) {
    HnValue r;
    if (a.type == HN_BOOL) r = hn_bool(!a.as.b);
    else { hn_free_value(a); return hn_type_err("`!` requires a bool"); }
    hn_free_value(a);
    return r;
}

static int hn_eq_raw(HnValue a, HnValue b) {
    if (a.type == HN_INT && b.type == HN_INT) return a.as.i == b.as.i;
    if (a.type == HN_FLOAT && b.type == HN_FLOAT) return a.as.f == b.as.f;
    if (a.type == HN_INT && b.type == HN_FLOAT) return (double)a.as.i == b.as.f;
    if (a.type == HN_FLOAT && b.type == HN_INT) return a.as.f == (double)b.as.i;
    if (a.type == HN_BOOL && b.type == HN_BOOL) return a.as.b == b.as.b;
    if (a.type == HN_STR && b.type == HN_STR) return strcmp(a.as.s->data, b.as.s->data) == 0;
    if (a.type == HN_NULL && b.type == HN_NULL) return 1;
    if (a.type == HN_LIST && b.type == HN_LIST) {
        HnList *x = a.as.list, *y = b.as.list;
        if (x->len != y->len) return 0;
        for (int i = 0; i < x->len; i++) if (!hn_eq_raw(x->items[i], y->items[i])) return 0;
        return 1;
    }
    if (a.type == HN_DICT && b.type == HN_DICT) {
        HnDict *x = a.as.dict, *y = b.as.dict;
        if (x->len != y->len) return 0;
        for (int i = 0; i < x->len; i++) {
            HnValue* p = hn_dict_getp(b, x->keys[i]);
            if (!p || !hn_eq_raw(x->vals[i], *p)) return 0;
        }
        return 1;
    }
    if (a.type == HN_ERR && b.type == HN_ERR) return a.as.err->code == b.as.err->code;
    return 0;
}

static HnValue hn_eq_v(HnValue a, HnValue b) { return hn_bool(hn_eq_raw(a, b)); }
static HnValue hn_ne_v(HnValue a, HnValue b) { return hn_bool(!hn_eq_raw(a, b)); }

static int hn_cmp_raw(HnValue a, HnValue b) {
    /* 返回 -1 / 0 / 1；类型不匹配返回 2 表示错误 */
    if (a.type == HN_INT && b.type == HN_INT) return a.as.i < b.as.i ? -1 : (a.as.i > b.as.i ? 1 : 0);
    if (a.type == HN_FLOAT && b.type == HN_FLOAT) return a.as.f < b.as.f ? -1 : (a.as.f > b.as.f ? 1 : 0);
    if (a.type == HN_INT && b.type == HN_FLOAT) return (double)a.as.i < b.as.f ? -1 : ((double)a.as.i > b.as.f ? 1 : 0);
    if (a.type == HN_FLOAT && b.type == HN_INT) return a.as.f < (double)b.as.i ? -1 : (a.as.f > (double)b.as.i ? 1 : 0);
    if (a.type == HN_STR && b.type == HN_STR) {
        int c = strcmp(a.as.s->data, b.as.s->data);
        return c < 0 ? -1 : (c > 0 ? 1 : 0);
    }
    return 2;
}

static HnValue hn_lt_v(HnValue a, HnValue b) { int c = hn_cmp_raw(a, b); hn_free_value(a); hn_free_value(b); return c == 2 ? hn_type_err("cannot compare operands") : hn_bool(c < 0); }
static HnValue hn_le_v(HnValue a, HnValue b) { int c = hn_cmp_raw(a, b); hn_free_value(a); hn_free_value(b); return c == 2 ? hn_type_err("cannot compare operands") : hn_bool(c <= 0); }
static HnValue hn_gt_v(HnValue a, HnValue b) { int c = hn_cmp_raw(a, b); hn_free_value(a); hn_free_value(b); return c == 2 ? hn_type_err("cannot compare operands") : hn_bool(c > 0); }
static HnValue hn_ge_v(HnValue a, HnValue b) { int c = hn_cmp_raw(a, b); hn_free_value(a); hn_free_value(b); return c == 2 ? hn_type_err("cannot compare operands") : hn_bool(c >= 0); }

/* ---------- 索引 / 字段 ---------- */
static HnValue hn_index_v(HnValue v, HnValue idx) {
    HnValue r = hn_null();
    if (idx.type != HN_INT) { hn_throw_value(hn_err_new(1, "index must be an int")); return r; }
    int64_t i = idx.as.i;
    if (v.type == HN_LIST) {
        HnList* l = v.as.list;
        if (i < 0 || i >= l->len) { hn_throw_value(hn_err_new(1, "index out of bounds")); return r; }
        r = hn_copy(l->items[i]);
    } else if (v.type == HN_STR) {
        int len = v.as.s->len;
        if (i < 0 || i >= len) { hn_throw_value(hn_err_new(1, "index out of bounds")); return r; }
        char c = v.as.s->data[i];
        r = hn_str_len(&c, 1);
    } else {
        hn_throw_value(hn_err_new(1, "cannot index a value of this type"));
        return r;
    }
    hn_free_value(v); hn_free_value(idx);
    return r;
}

/* 索引赋值：克隆容器并写入（保持拷贝语义），返回新容器；v/idx 被消费，val 所有权转移 */
static HnValue hn_index_set(HnValue v, HnValue idx, HnValue val) {
    if (idx.type != HN_INT) { hn_throw_value(hn_err_new(1, "index must be an int")); return hn_null(); }
    int64_t i = idx.as.i;
    if (v.type != HN_LIST) { hn_throw_value(hn_err_new(1, "index assignment requires a list")); return hn_null(); }
    HnList* l = v.as.list;
    if (i < 0 || i >= l->len) { hn_throw_value(hn_err_new(1, "index out of bounds")); return hn_null(); }
    HnValue n = hn_copy(v);
    hn_free_value(n.as.list->items[i]);
    n.as.list->items[i] = val;
    hn_free_value(v); hn_free_value(idx);
    return n;
}

/* 字段访问：dict 按键；error 取 code/message/file/line/col/context；v 被消费 */
static HnValue hn_field_v(HnValue v, const char* field) {
    HnValue r;
    if (v.type == HN_DICT) {
        HnValue* p = hn_dict_getp(v, field);
        if (p) { r = hn_copy(*p); hn_free_value(v); return r; }
        hn_throw_value(hn_err_new(2, "unknown field"));
        return hn_null();
    }
    if (v.type == HN_ERR) {
        HnErr* e = v.as.err;
        if (strcmp(field, "code") == 0) { r = hn_str(""); }
        else if (strcmp(field, "message") == 0) { r = hn_str(e->msg ? e->msg : ""); }
        else if (strcmp(field, "file") == 0) { r = hn_str(e->file ? e->file : ""); }
        else if (strcmp(field, "line") == 0) { r = hn_int(e->line); }
        else if (strcmp(field, "col") == 0) { r = hn_int(e->col); }
        else if (strcmp(field, "context") == 0) { r = hn_str(e->context ? e->context : ""); }
        else { hn_throw_value(hn_err_new(2, "unknown error field")); return hn_null(); }
        if (strcmp(field, "code") == 0) {
            char buf[16]; snprintf(buf, sizeof buf, "H%03d", e->code);
            hn_free_value(r);
            r = hn_str(buf);
        }
        hn_free_value(v);
        return r;
    }
    hn_throw_value(hn_err_new(1, "field access requires a dict or error value"));
    return hn_null();
}

/* ---------- 函数调用 ---------- */
static HnValue hn_call_fn(HnValue fn, HnValue* args, int nargs) {
    if (fn.type != HN_FN) { hn_throw_value(hn_err_new(2, "calling a non-function value")); return hn_null(); }
    HnValue r = fn.as.fn->ptr(args, nargs, fn.as.fn->cap, fn.as.fn->ncap);
    hn_free_value(fn);
    return r;
}

/* throw 语句的语义：str → H600 用户错误；error → 重抛；其余类型报错 */
static void hn_throw_expr(HnValue v) {
    if (v.type == HN_STR) {
        hn_throw_value(hn_err_new(600, v.as.s->data));
    } else if (v.type == HN_ERR) {
        hn_throw_value(v);
    } else {
        hn_throw_value(hn_err_new(1, "throw requires a str or error value"));
    }
}

/* 条件判断：Hone 要求 cond 为 bool */
static bool hn_is_true(HnValue v) {
    return v.type == HN_BOOL && v.as.b;
}

/* 循环/if 条件：求值并释放（生成器用于 while/for/if 条件表达式） */
static int hn_truthy(HnValue v) {
    int r = (v.type == HN_BOOL && v.as.b);
    hn_free_value(v);
    return r;
}

/* to_str 单值辅助（f-string / 拼接用）；消费参数 */
static HnValue hn_to_str_v(HnValue v) {
    char* s = hn_display(v);
    HnValue r = hn_str(s);
    free(s);
    hn_free_value(v);
    return r;
}

/* 构造闭包值：cap 数组所有权转移给闭包 */
static HnValue hn_fn_new(HnFnPtr ptr, HnValue* cap, int ncap) {
    HnValue v; v.type = HN_FN;
    HnFn* f = (HnFn*)malloc(sizeof(HnFn));
    f->refs = 1; f->ptr = ptr;
    f->ncap = ncap;
    f->cap = (HnValue*)malloc((size_t)(ncap ? ncap : 1) * sizeof(HnValue));
    for (int i = 0; i < ncap; i++) f->cap[i] = cap[i];
    v.as.fn = f;
    return v;
}

/* ---------- 核心内置（与 builtins.rs 语义一致） ---------- */
static HnValue hn_builtin_print(HnValue* args, int nargs) {
    if (nargs < 1) { hn_throw_value(hn_err_new(11, "print expects 1 argument")); return hn_null(); }
    char* s = hn_display(args[0]);
    fputs(s, stdout);
    fputc('\n', stdout);
    free(s);
    return hn_null();
}

static HnValue hn_builtin_len(HnValue* args, int nargs) {
    if (nargs < 1) { hn_throw_value(hn_err_new(11, "len expects 1 argument")); return hn_null(); }
    HnValue v = args[0];
    if (v.type == HN_LIST) return hn_int(v.as.list->len);
    if (v.type == HN_DICT) return hn_int(v.as.dict->len);
    if (v.type == HN_STR) return hn_int(v.as.s->len);
    if (v.type == HN_NULL) return hn_int(0);
    hn_throw_value(hn_err_new(1, "len requires a list, dict or str"));
    return hn_null();
}

static HnValue hn_builtin_to_str(HnValue* args, int nargs) {
    if (nargs < 1) { hn_throw_value(hn_err_new(11, "to_str expects 1 argument")); return hn_null(); }
    char* s = hn_display(args[0]);
    HnValue r = hn_str(s);
    free(s);
    return r;
}

static HnValue hn_builtin_to_int(HnValue* args, int nargs) {
    if (nargs < 1) { hn_throw_value(hn_err_new(11, "to_int expects 1 argument")); return hn_null(); }
    HnValue v = args[0];
    if (v.type == HN_INT) return hn_int(v.as.i);
    if (v.type == HN_FLOAT) return hn_int((int64_t)v.as.f);
    if (v.type == HN_STR) {
        char* end = NULL;
        long long r = strtoll(v.as.s->data, &end, 10);
        if (end == v.as.s->data || *end != '\0') {
            hn_throw_value(hn_err_new(6, "cannot convert string to int"));
            return hn_null();
        }
        return hn_int((int64_t)r);
    }
    if (v.type == HN_BOOL) return hn_int(v.as.b ? 1 : 0);
    hn_throw_value(hn_err_new(6, "cannot convert value to int"));
    return hn_null();
}

static HnValue hn_builtin_to_float(HnValue* args, int nargs) {
    if (nargs < 1) { hn_throw_value(hn_err_new(11, "to_float expects 1 argument")); return hn_null(); }
    HnValue v = args[0];
    if (v.type == HN_FLOAT) return hn_float(v.as.f);
    if (v.type == HN_INT) return hn_float((double)v.as.i);
    if (v.type == HN_STR) {
        char* end = NULL;
        double r = strtod(v.as.s->data, &end);
        if (end == v.as.s->data || *end != '\0') {
            hn_throw_value(hn_err_new(6, "cannot convert string to float"));
            return hn_null();
        }
        return hn_float(r);
    }
    hn_throw_value(hn_err_new(6, "cannot convert value to float"));
    return hn_null();
}

static HnValue hn_builtin_type_of(HnValue* args, int nargs) {
    if (nargs < 1) { hn_throw_value(hn_err_new(11, "type_of expects 1 argument")); return hn_null(); }
    return hn_str(hn_type_name(args[0]));
}

static HnValue hn_builtin_is(HnValue* args, int nargs, int t) {
    if (nargs < 1) { hn_throw_value(hn_err_new(11, "is_* expects 1 argument")); return hn_null(); }
    return hn_bool(args[0].type == t);
}

static HnValue hn_builtin_append(HnValue* args, int nargs) {
    if (nargs < 2) { hn_throw_value(hn_err_new(11, "append expects 2 arguments")); return hn_null(); }
    if (args[0].type != HN_LIST) { hn_throw_value(hn_err_new(1, "append requires a list")); return hn_null(); }
    HnValue n = hn_copy(args[0]);
    hn_list_push(n, hn_copy(args[1]));
    return n;
}

static HnValue hn_builtin_contains(HnValue* args, int nargs) {
    if (nargs < 2) { hn_throw_value(hn_err_new(11, "contains expects 2 arguments")); return hn_null(); }
    HnValue v = args[0];
    if (v.type == HN_LIST) {
        HnList* l = v.as.list;
        for (int i = 0; i < l->len; i++) if (hn_eq_raw(l->items[i], args[1])) return hn_bool(true);
        return hn_bool(false);
    }
    if (v.type == HN_STR) {
        return hn_bool(strstr(v.as.s->data, args[1].as.s->data) != NULL);
    }
    if (v.type == HN_DICT) {
        return hn_bool(hn_dict_find(v.as.dict, args[1].as.s->data) >= 0);
    }
    hn_throw_value(hn_err_new(1, "contains requires a list, dict or str"));
    return hn_null();
}

static HnValue hn_builtin_keys(HnValue* args, int nargs) {
    if (nargs < 1 || args[0].type != HN_DICT) { hn_throw_value(hn_err_new(1, "keys requires a dict")); return hn_null(); }
    HnDict* d = args[0].as.dict;
    HnValue n = hn_list_new();
    for (int i = 0; i < d->len; i++) hn_list_push(n, hn_str(d->keys[i]));
    return n;
}

static HnValue hn_builtin_values(HnValue* args, int nargs) {
    if (nargs < 1 || args[0].type != HN_DICT) { hn_throw_value(hn_err_new(1, "values requires a dict")); return hn_null(); }
    HnDict* d = args[0].as.dict;
    HnValue n = hn_list_new();
    for (int i = 0; i < d->len; i++) hn_list_push(n, hn_copy(d->vals[i]));
    return n;
}

static HnValue hn_builtin_has_key(HnValue* args, int nargs) {
    if (nargs < 2 || args[0].type != HN_DICT) { hn_throw_value(hn_err_new(1, "has_key requires a dict")); return hn_null(); }
    return hn_bool(hn_dict_find(args[0].as.dict, args[1].as.s->data) >= 0);
}

static HnValue hn_builtin_abs(HnValue* args, int nargs) {
    if (nargs < 1) { hn_throw_value(hn_err_new(11, "abs expects 1 argument")); return hn_null(); }
    if (args[0].type == HN_INT) return hn_int(args[0].as.i < 0 ? -args[0].as.i : args[0].as.i);
    if (args[0].type == HN_FLOAT) return hn_float(args[0].as.f < 0 ? -args[0].as.f : args[0].as.f);
    hn_throw_value(hn_err_new(1, "abs requires a number"));
    return hn_null();
}

static HnValue hn_builtin_max(HnValue* args, int nargs) {
    if (nargs < 2) { hn_throw_value(hn_err_new(11, "max expects 2 arguments")); return hn_null(); }
    int c = hn_cmp_raw(args[0], args[1]);
    if (c == 2) { hn_throw_value(hn_err_new(1, "cannot compare operands")); return hn_null(); }
    return hn_copy(c >= 0 ? args[0] : args[1]);
}

static HnValue hn_builtin_min(HnValue* args, int nargs) {
    if (nargs < 2) { hn_throw_value(hn_err_new(11, "min expects 2 arguments")); return hn_null(); }
    int c = hn_cmp_raw(args[0], args[1]);
    if (c == 2) { hn_throw_value(hn_err_new(1, "cannot compare operands")); return hn_null(); }
    return hn_copy(c <= 0 ? args[0] : args[1]);
}

static HnValue hn_builtin_str_contains(HnValue* args, int nargs) {
    if (nargs < 2) { hn_throw_value(hn_err_new(11, "str_contains expects 2 arguments")); return hn_null(); }
    if (args[0].type != HN_STR || args[1].type != HN_STR) { hn_throw_value(hn_err_new(1, "str_contains requires strings")); return hn_null(); }
    return hn_bool(strstr(args[0].as.s->data, args[1].as.s->data) != NULL);
}

static HnValue hn_builtin_str_replace(HnValue* args, int nargs) {
    if (nargs < 3) { hn_throw_value(hn_err_new(11, "str_replace expects 3 arguments")); return hn_null(); }
    if (args[0].type != HN_STR || args[1].type != HN_STR || args[2].type != HN_STR) {
        hn_throw_value(hn_err_new(1, "str_replace requires strings"));
        return hn_null();
    }
    const char* hay = args[0].as.s->data;
    const char* needle = args[1].as.s->data;
    const char* rep = args[2].as.s->data;
    if (*needle == '\0') return hn_str(hay);
    size_t hnlen = strlen(needle), rlen = strlen(rep), count = 0;
    const char* p = hay;
    while ((p = strstr(p, needle)) != NULL) { count++; p += hnlen; }
    size_t outlen = strlen(hay) + count * (rlen - hnlen);
    char* out = (char*)malloc(outlen + 1);
    char* q = out;
    p = hay;
    const char* scan = hay;
    while ((p = strstr(scan, needle)) != NULL) {
        size_t n = (size_t)(p - scan);
        memcpy(q, scan, n); q += n;
        memcpy(q, rep, rlen); q += rlen;
        scan = p + hnlen;
    }
    strcpy(q, scan);
    HnValue r = hn_str(out);
    free(out);
    return r;
}

static HnValue hn_builtin_str_trim(HnValue* args, int nargs) {
    if (nargs < 1 || args[0].type != HN_STR) { hn_throw_value(hn_err_new(1, "str_trim requires a string")); return hn_null(); }
    const char* s = args[0].as.s->data;
    while (*s == ' ' || *s == '\t' || *s == '\n' || *s == '\r') s++;
    size_t n = strlen(s);
    while (n > 0 && (s[n-1] == ' ' || s[n-1] == '\t' || s[n-1] == '\n' || s[n-1] == '\r')) n--;
    return hn_str_len(s, (int)n);
}

static HnValue hn_builtin_read_file(HnValue* args, int nargs) {
    if (nargs < 1 || args[0].type != HN_STR) { hn_throw_value(hn_err_new(1, "read_file requires a path")); return hn_null(); }
    FILE* f = fopen(args[0].as.s->data, "rb");
    if (!f) { hn_throw_value(hn_err_new(401, "file not found")); return hn_null(); }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc((size_t)sz + 1);
    size_t rd = fread(buf, 1, (size_t)sz, f);
    buf[rd] = '\0';
    fclose(f);
    return hn_str_len(buf, (int)rd);
}

static HnValue hn_builtin_write_file(HnValue* args, int nargs) {
    if (nargs < 2 || args[0].type != HN_STR || args[1].type != HN_STR) {
        hn_throw_value(hn_err_new(1, "write_file requires a path and content"));
        return hn_null();
    }
    FILE* f = fopen(args[0].as.s->data, "wb");
    if (!f) { hn_throw_value(hn_err_new(401, "cannot open file for writing")); return hn_null(); }
    fwrite(args[1].as.s->data, 1, (size_t)args[1].as.s->len, f);
    fclose(f);
    return hn_bool(true);
}

static HnValue hn_builtin_file_exists(HnValue* args, int nargs) {
    if (nargs < 1 || args[0].type != HN_STR) { hn_throw_value(hn_err_new(1, "file_exists requires a path")); return hn_null(); }
    FILE* f = fopen(args[0].as.s->data, "rb");
    if (f) { fclose(f); return hn_bool(true); }
    return hn_bool(false);
}

static HnValue hn_builtin_read_bytes(HnValue* args, int nargs) {
    if (nargs < 1 || args[0].type != HN_STR) { hn_throw_value(hn_err_new(1, "read_bytes requires a path")); return hn_null(); }
    FILE* f = fopen(args[0].as.s->data, "rb");
    if (!f) { hn_throw_value(hn_err_new(401, "file not found")); return hn_null(); }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    HnValue r = hn_list_new();
    if (sz > 0) {
        unsigned char* buf = (unsigned char*)malloc((size_t)sz);
        size_t rd = fread(buf, 1, (size_t)sz, f);
        for (size_t i = 0; i < rd; i++) hn_list_push(r, hn_int(buf[i]));
        free(buf);
    }
    fclose(f);
    return r;
}

static HnValue hn_builtin_write_bytes(HnValue* args, int nargs) {
    if (nargs < 2 || args[0].type != HN_STR || args[1].type != HN_LIST) {
        hn_throw_value(hn_err_new(1, "write_bytes requires a path and a byte list"));
        return hn_null();
    }
    HnList* l = args[1].as.list;
    FILE* f = fopen(args[0].as.s->data, "wb");
    if (!f) { hn_throw_value(hn_err_new(401, "cannot open file for writing")); return hn_null(); }
    for (int i = 0; i < l->len; i++) {
        if (l->items[i].type != HN_INT) { fclose(f); hn_throw_value(hn_err_new(1, "write_bytes expects integer byte values 0..255")); return hn_null(); }
        int64_t b = l->items[i].as.i;
        if (b < 0 || b > 255) { fclose(f); hn_throw_value(hn_err_new(1, "write_bytes byte value out of range 0..255")); return hn_null(); }
        fputc((int)b, f);
    }
    fclose(f);
    return hn_null();
}

static HnValue hn_builtin_input(HnValue* args, int nargs) {
    if (nargs >= 1 && args[0].type == HN_STR) {
        char* s = hn_display(args[0]);
        fputs(s, stdout);
        free(s);
    }
    char buf[4096];
    if (!fgets(buf, sizeof buf, stdin)) return hn_str("");
    size_t n = strlen(buf);
    while (n > 0 && (buf[n-1] == '\n' || buf[n-1] == '\r')) n--;
    return hn_str_len(buf, (int)n);
}

static HnValue hn_builtin_read_int(HnValue* args, int nargs) {
    HnValue s = hn_builtin_input(args, nargs);
    char* end = NULL;
    long long r = strtoll(s.as.s->data, &end, 10);
    if (end == s.as.s->data) { hn_free_value(s); hn_throw_value(hn_err_new(6, "cannot parse int")); return hn_null(); }
    hn_free_value(s);
    return hn_int((int64_t)r);
}

static HnValue hn_builtin_read_float(HnValue* args, int nargs) {
    HnValue s = hn_builtin_input(args, nargs);
    char* end = NULL;
    double r = strtod(s.as.s->data, &end);
    if (end == s.as.s->data) { hn_free_value(s); hn_throw_value(hn_err_new(6, "cannot parse float")); return hn_null(); }
    hn_free_value(s);
    return hn_float(r);
}

static HnValue hn_builtin_index_of(HnValue* args, int nargs) {
    if (nargs < 2 || args[0].type != HN_LIST) { hn_throw_value(hn_err_new(1, "index_of requires a list")); return hn_null(); }
    HnList* l = args[0].as.list;
    for (int i = 0; i < l->len; i++) if (hn_eq_raw(l->items[i], args[1])) return hn_int(i);
    return hn_int(-1);
}

static HnValue hn_builtin_assert(HnValue* args, int nargs) {
    if (nargs < 1) { hn_throw_value(hn_err_new(11, "assert expects 1 argument")); return hn_null(); }
    if (args[0].type != HN_BOOL || !args[0].as.b) {
        hn_throw_value(hn_err_new(700, "assertion failed"));
        return hn_null();
    }
    return hn_null();
}

static HnValue hn_builtin_time_now(HnValue* args, int nargs) {
    (void)args; (void)nargs;
    return hn_int((int64_t)time(NULL));
}

static HnValue hn_builtin_time_sleep(HnValue* args, int nargs) {
    if (nargs < 1) { hn_throw_value(hn_err_new(11, "time.sleep expects 1 argument")); return hn_null(); }
    double secs = args[0].type == HN_INT ? (double)args[0].as.i : (args[0].type == HN_FLOAT ? args[0].as.f : -1.0);
    if (secs < 0) { hn_throw_value(hn_err_new(1, "time.sleep requires a number")); return hn_null(); }
#ifdef _WIN32
    Sleep((DWORD)(secs * 1000.0));
#else
    long nanos = (long)(secs * 1000000000.0);
    struct timespec ts;
    ts.tv_sec = nanos / 1000000000L;
    ts.tv_nsec = nanos % 1000000000L;
    nanosleep(&ts, NULL);
#endif
    return hn_null();
}

static uint64_t hn_rng_state = 0x9E3779B97F4A7C15ULL;
static void hn_rng_seed(void) {
    if (hn_rng_state == 0x9E3779B97F4A7C15ULL) hn_rng_state ^= (uint64_t)time(NULL) ^ ((uint64_t)time(NULL) << 21);
}
static uint64_t hn_rng_next(void) {
    hn_rng_state ^= hn_rng_state >> 12;
    hn_rng_state ^= hn_rng_state << 25;
    hn_rng_state ^= hn_rng_state >> 27;
    return hn_rng_state * 2685821657736338717ULL;
}

static HnValue hn_builtin_random_int(HnValue* args, int nargs) {
    (void)nargs;
    hn_rng_seed();
    int64_t r = (int64_t)(hn_rng_next() & 0x7FFFFFFFFFFFFFFFULL);
    if (nargs >= 2 && args[0].type == HN_INT && args[1].type == HN_INT) {
        int64_t lo = args[0].as.i, hi = args[1].as.i;
        if (hi <= lo) { hn_throw_value(hn_err_new(1, "random.int range requires hi > lo")); return hn_null(); }
        return hn_int(lo + r % (hi - lo));
    }
    return hn_int(r);
}

static HnValue hn_builtin_random_float(HnValue* args, int nargs) {
    (void)args; (void)nargs;
    hn_rng_seed();
    return hn_float((double)(hn_rng_next() >> 11) / 9007199254740992.0);
}

/* ---------- 内置分发 ---------- */
static HnValue hn_call_builtin(const char* name, HnValue* args, int nargs) {
    if (strcmp(name, "print") == 0) return hn_builtin_print(args, nargs);
    if (strcmp(name, "len") == 0) return hn_builtin_len(args, nargs);
    if (strcmp(name, "to_str") == 0) return hn_builtin_to_str(args, nargs);
    if (strcmp(name, "to_int") == 0) return hn_builtin_to_int(args, nargs);
    if (strcmp(name, "to_float") == 0) return hn_builtin_to_float(args, nargs);
    if (strcmp(name, "type_of") == 0) return hn_builtin_type_of(args, nargs);
    if (strcmp(name, "is_int") == 0) return hn_builtin_is(args, nargs, HN_INT);
    if (strcmp(name, "is_float") == 0) return hn_builtin_is(args, nargs, HN_FLOAT);
    if (strcmp(name, "is_bool") == 0) return hn_builtin_is(args, nargs, HN_BOOL);
    if (strcmp(name, "is_str") == 0) return hn_builtin_is(args, nargs, HN_STR);
    if (strcmp(name, "is_list") == 0) return hn_builtin_is(args, nargs, HN_LIST);
    if (strcmp(name, "is_dict") == 0) return hn_builtin_is(args, nargs, HN_DICT);
    if (strcmp(name, "is_null") == 0) return hn_builtin_is(args, nargs, HN_NULL);
    if (strcmp(name, "append") == 0) return hn_builtin_append(args, nargs);
    if (strcmp(name, "contains") == 0) return hn_builtin_contains(args, nargs);
    if (strcmp(name, "index_of") == 0) return hn_builtin_index_of(args, nargs);
    if (strcmp(name, "keys") == 0) return hn_builtin_keys(args, nargs);
    if (strcmp(name, "values") == 0) return hn_builtin_values(args, nargs);
    if (strcmp(name, "has_key") == 0) return hn_builtin_has_key(args, nargs);
    if (strcmp(name, "abs") == 0) return hn_builtin_abs(args, nargs);
    if (strcmp(name, "max") == 0) return hn_builtin_max(args, nargs);
    if (strcmp(name, "min") == 0) return hn_builtin_min(args, nargs);
    if (strcmp(name, "str_contains") == 0) return hn_builtin_str_contains(args, nargs);
    if (strcmp(name, "str_replace") == 0) return hn_builtin_str_replace(args, nargs);
    if (strcmp(name, "str_trim") == 0) return hn_builtin_str_trim(args, nargs);
    if (strcmp(name, "read_file") == 0) return hn_builtin_read_file(args, nargs);
    if (strcmp(name, "write_file") == 0) return hn_builtin_write_file(args, nargs);
    if (strcmp(name, "file_exists") == 0) return hn_builtin_file_exists(args, nargs);
    if (strcmp(name, "read_bytes") == 0) return hn_builtin_read_bytes(args, nargs);
    if (strcmp(name, "write_bytes") == 0) return hn_builtin_write_bytes(args, nargs);
    if (strcmp(name, "input") == 0) return hn_builtin_input(args, nargs);
    if (strcmp(name, "read_int") == 0) return hn_builtin_read_int(args, nargs);
    if (strcmp(name, "read_float") == 0) return hn_builtin_read_float(args, nargs);
    if (strcmp(name, "assert") == 0) return hn_builtin_assert(args, nargs);
    if (strcmp(name, "clone") == 0 || strcmp(name, "copy") == 0) {
        if (nargs < 1) { hn_throw_value(hn_err_new(11, "clone expects 1 argument")); return hn_null(); }
        return hn_copy(args[0]);
    }
    if (strcmp(name, "time.now") == 0) return hn_builtin_time_now(args, nargs);
    if (strcmp(name, "time.sleep") == 0) return hn_builtin_time_sleep(args, nargs);
    if (strcmp(name, "random.int") == 0) return hn_builtin_random_int(args, nargs);
    if (strcmp(name, "random.float") == 0) return hn_builtin_random_float(args, nargs);
    /* 其余内置在 AOT 编译期已报"暂不支持"，此处兜底 */
    {
        char buf[256];
        snprintf(buf, sizeof buf, "builtin `%s` is not supported in AOT builds", name);
        hn_throw_value(hn_err_new(999, buf));
        return hn_null();
    }
}
"##;

// ===================== AOT 代码生成（Rust AST → C） =====================
// 生成器将已通过 parser + checker 检查的 Hone AST 翻译为 C 源码：
//   - 值模型/内存/内置函数全部来自上面内嵌的 RUNTIME_C
//   - 每个 Hone 函数 → static HnValue hn_f<idx>(HnValue* args, int nargs, HnValue* cap, int ncap)
//     args 由调用方构造（被调函数消费，不释放）；cap 为 lambda 捕获环境（被调函数只读）
//   - 变量 → 局部 HnValue vN；读取 = hn_copy（拷贝语义，与解释器一致）；重新赋值先释放旧值
//   - 块级作用域与 C 的 { } 一一对应；循环/if 条件用 hn_truthy（求值并释放）
//   - 核心内置直接分发；重内置在编译期报"暂不支持"
// 内存说明（v1）：int/float/bool/null 无堆分配零泄漏；str/list/dict 在赋值时释放旧值，
// 函数返回时不释放局部变量（递归字符串密集脚本可能累积，文档已注明）。

/// 收集到的函数定义（参数 + 函数体）
#[derive(Clone)]
struct AotFn {
    params: Vec<Param>,
    body: Vec<Stmt>,
}

/// 生成器状态：跨函数共享的定义表 + 每次生成单个函数时重置的局部状态
struct AotGen {
    file: String,
    src: String,
    // ---- 定义表（收集阶段填充，生成阶段只读） ----
    fns: HashMap<String, AotFn>,              // 全局函数名 → 定义
    structs: HashMap<String, Vec<String>>,    // 结构体名 → 字段名
    classes: HashMap<String, Vec<(String, AotFn)>>, // 类名 → 方法列表
    alias: HashMap<String, String>,           // 函数别名（新名 → 原名）
    fn_slots: HashMap<String, usize>,         // 函数/类方法全名 → 槽位
    // ---- 生成阶段局部状态（每函数重置） ----
    out: String,                              // 当前函数体输出
    scopes: Vec<HashMap<String, String>>,     // 变量名 → C 变量名（vN）
    var_counter: usize,
    temp_counter: usize,
    // ---- 全局计数器 ----
    lambda_counter: usize,
    lambda_out: String,                       // lambda 函数实现（main 之前输出）
    try_saves: Vec<String>,                   // 活跃 try 的保存变量名栈（hn_jmp_top 恢复）
    loop_saves: Vec<String>,                  // 活跃循环入口保存的 jmp_buf* 变量名（break/continue 恢复）
    cont_targets: Vec<Option<String>>,        // 当前循环的 continue 目标（None=C continue；Some=goto 标签）
    builtin_err: Option<(String, Span)>,      // 首次遇到的"暂不支持"内置（延迟报错）
}

/// 生成完整 C 源码。调用方必须已执行 parser + checker 检查。
pub fn generate(program: &Program, file: &str, src: &str) -> Result<String, ZError> {
    let mut g = AotGen {
        file: file.to_string(),
        src: src.to_string(),
        fns: HashMap::new(),
        structs: HashMap::new(),
        classes: HashMap::new(),
        alias: HashMap::new(),
        fn_slots: HashMap::new(),
        out: String::new(),
        scopes: Vec::new(),
        var_counter: 0,
        temp_counter: 0,
        lambda_counter: 0,
        lambda_out: String::new(),
        try_saves: Vec::new(),
        loop_saves: Vec::new(),
        cont_targets: Vec::new(),
        builtin_err: None,
    };
    g.collect_defs(&program.stmts)?;

    // 预分配槽位：用户函数 + 类方法（"类.方法" 全名）
    let mut names: Vec<String> = g.fns.keys().cloned().collect();
    for (cls, methods) in &g.classes {
        for (m, _) in methods {
            names.push(format!("{}.{}", cls, m));
        }
    }
    names.sort();
    for n in &names {
        g.slot_for(n);
    }

    let mut c = String::new();
    c.push_str(RUNTIME_C);
    c.push_str("\n");

    // 原型（递归/相互调用需要）：所有用户函数与类方法
    let mut slots: Vec<(String, usize)> = g.fn_slots.iter().map(|(k, v)| (k.clone(), *v)).collect();
    slots.sort_by_key(|(_, v)| *v);
    for (name, _) in &slots {
        let cname = format!("hn_f{}", g.fn_slots[name]);
        c.push_str(&format!("static HnValue {}(HnValue* args, int nargs, HnValue* cap, int ncap);\n", cname));
    }
    // lambda 原型：数量需预扫描（生成顺序与预扫描一致，均为深度优先）
    let lambda_total = count_lambdas(&program.stmts, &g.fns, &g.classes);
    for i in 0..lambda_total {
        c.push_str(&format!("static HnValue hn_lm{}(HnValue* args, int nargs, HnValue* cap, int ncap);\n", i));
    }

    // 各函数实现（按槽位顺序）
    for (name, _) in &slots {
        let impl_text = g.gen_function(name)?;
        c.push_str(&impl_text);
        c.push_str("\n");
    }
    // lambda 实现（main 之前输出）
    c.push_str(&g.lambda_out);

    // main()：执行顶层语句；若顶层无语句且有 main 函数则调用之
    c.push_str("int main(void) {\n");
    g.reset_state();
    let mut main_body = String::new();
    g.gen_stmts(&program.stmts, &mut main_body)?;
    if main_body.trim().is_empty() {
        if let Some(slot) = g.fn_slots.get("main") {
            main_body.push_str(&format!(
                "    HnValue _r = hn_f{}(NULL, 0, NULL, 0);\n    hn_free_value(_r);\n",
                slot
            ));
        }
    }
    c.push_str(&main_body);
    c.push_str("    return 0;\n}\n");

    if let Some((b, sp)) = g.builtin_err {
        return Err(zerr(
            &g.file,
            &g.src,
            codes::NOT_IMPLEMENTED,
            format!("内置函数 `{}` 在 AOT 模式暂不支持", b),
            sp,
            Some("AOT 模式仅支持核心内置；请用解释器运行，或改用 print/len/to_str 等核心函数"),
        ));
    }
    Ok(c)
}

/// 构造带定位的错误
fn zerr(
    file: &str,
    src: &str,
    code: &'static str,
    msg: String,
    span: Span,
    help: Option<impl Into<String>>,
) -> ZError {
    ZError::new(code, msg, file, src, span.line, span.col, span.len.max(1), help)
}

/// 预扫描统计 lambda 数量（深度优先，与生成顺序一致；含类方法体）
fn count_lambdas(
    stmts: &[Stmt],
    fns: &HashMap<String, AotFn>,
    classes: &HashMap<String, Vec<(String, AotFn)>>,
) -> usize {
    let mut n = 0;
    count_lambdas_stmts(stmts, &mut n);
    for f in fns.values() {
        count_lambdas_stmts(&f.body, &mut n);
    }
    for methods in classes.values() {
        for (_, f) in methods {
            count_lambdas_stmts(&f.body, &mut n);
        }
    }
    n
}

fn count_lambdas_stmts(stmts: &[Stmt], n: &mut usize) {
    for s in stmts {
        match s {
            Stmt::Assign { value, .. } => count_lambdas_expr(value, n),
            Stmt::IndexAssign { target, value, .. } => {
                count_lambdas_expr(target, n);
                count_lambdas_expr(value, n);
            }
            Stmt::DestructAssign { value, .. } => count_lambdas_expr(value, n),
            Stmt::AssignOp { value, .. } => count_lambdas_expr(value, n),
            Stmt::VarDecl { init, .. } => {
                if let Some(i) = init {
                    count_lambdas_expr(i, n);
                }
            }
            Stmt::Block { stmts, .. } => count_lambdas_stmts(stmts, n),
            Stmt::If { cond, then_branch, else_branch, .. } => {
                count_lambdas_expr(cond, n);
                count_lambdas_stmts(then_branch, n);
                if let Some(eb) = else_branch {
                    count_lambdas_stmts(eb, n);
                }
            }
            Stmt::While { cond, body, .. } => {
                count_lambdas_expr(cond, n);
                count_lambdas_stmts(body, n);
            }
            Stmt::DoWhile { body, cond, .. } => {
                count_lambdas_stmts(body, n);
                count_lambdas_expr(cond, n);
            }
            Stmt::ForC { init, cond, step, body, .. } => {
                if let Some(i) = init {
                    count_lambdas_stmts(std::slice::from_ref(i.as_ref()), n);
                }
                if let Some(c) = cond {
                    count_lambdas_expr(c, n);
                }
                if let Some(s) = step {
                    count_lambdas_stmts(std::slice::from_ref(s.as_ref()), n);
                }
                count_lambdas_stmts(body, n);
            }
            Stmt::ForIn { iter, body, .. } => {
                count_lambdas_expr(iter, n);
                count_lambdas_stmts(body, n);
            }
            Stmt::Return { values, .. } => {
                for v in values {
                    count_lambdas_expr(v, n);
                }
            }
            Stmt::DebugPrint { expr, .. } => count_lambdas_expr(expr, n),
            Stmt::ExprStmt { expr, .. } => count_lambdas_expr(expr, n),
            Stmt::Breakpoint { cond, .. } => {
                if let Some(c) = cond {
                    count_lambdas_expr(c, n);
                }
            }
            Stmt::Go { args, .. } => {
                for a in args {
                    count_lambdas_expr(a, n);
                }
            }
            Stmt::Try { body, handler, .. } => {
                count_lambdas_stmts(body, n);
                count_lambdas_stmts(handler, n);
            }
            Stmt::Throw { value, .. } => count_lambdas_expr(value, n),
            Stmt::FnDef { body, .. } => count_lambdas_stmts(body, n),
            _ => {}
        }
    }
}

fn count_lambdas_expr(e: &Expr, n: &mut usize) {
    match e {
        Expr::ListLit(items, _) => {
            for i in items {
                count_lambdas_expr(i, n);
            }
        }
        Expr::DictLit(entries, _) => {
            for (_, v) in entries {
                count_lambdas_expr(v, n);
            }
        }
        Expr::ListComp { elem, iter, cond, .. } => {
            count_lambdas_expr(elem, n);
            count_lambdas_expr(iter, n);
            if let Some(c) = cond {
                count_lambdas_expr(c, n);
            }
        }
        Expr::DictComp { key, value, iter, cond, .. } => {
            count_lambdas_expr(key, n);
            count_lambdas_expr(value, n);
            count_lambdas_expr(iter, n);
            if let Some(c) = cond {
                count_lambdas_expr(c, n);
            }
        }
        Expr::FStr(segs, _) => {
            for s in segs {
                if let FStrSeg::Code(e) = s {
                    count_lambdas_expr(e, n);
                }
            }
        }
        Expr::Field { obj, .. } | Expr::OptionalField { obj, .. } | Expr::Unary { expr: obj, .. } => {
            count_lambdas_expr(obj, n);
        }
        Expr::Index { obj, index, .. } => {
            count_lambdas_expr(obj, n);
            count_lambdas_expr(index, n);
        }
        Expr::Binary { lhs, rhs, .. } => {
            count_lambdas_expr(lhs, n);
            count_lambdas_expr(rhs, n);
        }
        Expr::Call { args, .. } => {
            for a in args {
                count_lambdas_expr(a, n);
            }
        }
        Expr::Match { value, arms, .. } => {
            count_lambdas_expr(value, n);
            for (_, body) in arms {
                count_lambdas_expr(body, n);
            }
        }
        Expr::Ternary { cond, then_expr, else_expr, .. } => {
            count_lambdas_expr(cond, n);
            count_lambdas_expr(then_expr, n);
            count_lambdas_expr(else_expr, n);
        }
        Expr::Lambda { body, .. } => {
            *n += 1;
            count_lambdas_stmts(body, n);
        }
        _ => {}
    }
}

impl AotGen {
    /// 收集函数/结构体/类/别名定义（与解释器 collect_* 一致：FnDef 扁平注册）
    fn collect_defs(&mut self, stmts: &[Stmt]) -> Result<(), ZError> {
        for s in stmts {
            match s {
                Stmt::FnDef { name, params, body, tmp, span, .. } => {
                    if !tmp {
                        if self.fns.contains_key(name) {
                            return Err(zerr(
                                &self.file,
                                &self.src,
                                codes::SYNTAX,
                                format!("duplicate function `{}`", name),
                                *span,
                                Some("函数名需全局唯一"),
                            ));
                        }
                        self.fns.insert(
                            name.clone(),
                            AotFn {
                                params: params.clone(),
                                body: body.clone(),
                            },
                        );
                    }
                }
                Stmt::StructDef { name, fields, .. } => {
                    self.structs.insert(name.clone(), fields.iter().map(|(f, _)| f.clone()).collect());
                }
                Stmt::ClassDef { name, methods, .. } => {
                    let mut list = Vec::new();
                    for m in methods {
                        if let Stmt::FnDef { name: mname, params, body, tmp, .. } = m {
                            if !tmp {
                                list.push((
                                    mname.clone(),
                                    AotFn {
                                        params: params.clone(),
                                        body: body.clone(),
                                    },
                                ));
                            }
                        }
                    }
                    self.classes.insert(name.clone(), list);
                }
                Stmt::Alias { original, new_name, .. } => {
                    self.alias.insert(new_name.clone(), original.clone());
                }
                Stmt::Block { stmts, .. } => self.collect_defs(stmts)?,
                Stmt::If { then_branch, else_branch, .. } => {
                    self.collect_defs(then_branch)?;
                    if let Some(eb) = else_branch {
                        self.collect_defs(eb)?;
                    }
                }
                Stmt::While { body, .. } => self.collect_defs(body)?,
                Stmt::ForIn { body, .. } => self.collect_defs(body)?,
                Stmt::Try { body, handler, .. } => {
                    self.collect_defs(body)?;
                    self.collect_defs(handler)?;
                }
                _ => {}
            }
        }
        Ok(())
    }

    /// 分配槽位（含类方法全名 "类.方法"），返回该函数的 C 函数名
    fn slot_for(&mut self, name: &str) -> usize {
        let next = self.fn_slots.len();
        *self.fn_slots.entry(name.to_string()).or_insert(next)
    }

    /// 生成单个 Hone 函数的 C 实现（支持 "类.方法" 全名）
    fn gen_function(&mut self, name: &str) -> Result<String, ZError> {
        let slot = self.slot_for(name);
        let cname = format!("hn_f{}", slot);
        let f = self.fn_lookup(name).ok_or_else(|| {
            zerr(
                &self.file,
                &self.src,
                codes::UNDEFINED,
                format!("internal: missing function `{}`", name),
                Span { line: 1, col: 1, len: 1 },
                None::<&str>,
            )
        })?;

        self.reset_state();
        let mut body = String::new();
        // 函数级 jmp 保存：return 前恢复（try/catch 的 jmp_buf 在栈上，不能悬挂）
        body.push_str("    jmp_buf* _fsave = hn_jmp_top;\n");
        // 参数：复制 args（调用方负责释放数组元素）；缺省参数用默认表达式
        for (i, p) in f.params.iter().enumerate() {
            let vname = format!("v{}", self.var_counter);
            self.var_counter += 1;
            self.scopes
                .last_mut()
                .expect("scope")
                .insert(p.name.clone(), vname.clone());
            let init = match &p.default {
                Some(d) => {
                    let de = self.gen_expr(d)?;
                    format!("(nargs > {} ? hn_copy(args[{}]) : {})", i, i, de)
                }
                None => format!("(nargs > {} ? hn_copy(args[{}]) : hn_null())", i, i),
            };
            body.push_str(&format!("    HnValue {} = {};\n", vname, init));
        }
        self.gen_stmts(&f.body, &mut body)?;
        // 隐式 return null（无返回值函数）
        body.push_str("    return hn_null();\n");
        let mut text = String::new();
        text.push_str(&format!("static HnValue {}(HnValue* args, int nargs, HnValue* cap, int ncap) {{\n", cname));
        text.push_str("    (void)cap; (void)ncap;\n");
        text.push_str(&body);
        text.push_str("}\n");
        Ok(text)
    }

    /// 重置单函数生成状态
    fn reset_state(&mut self) {
        self.out.clear();
        self.scopes.clear();
        self.scopes.push(HashMap::new());
        self.var_counter = 0;
        self.temp_counter = 0;
        self.try_saves.clear();
        self.loop_saves.clear();
        self.cont_targets.clear();
    }

    /// 新临时变量名
    fn temp(&mut self) -> String {
        let t = format!("_t{}", self.temp_counter);
        self.temp_counter += 1;
        t
    }

    /// 生成一组语句
    fn gen_stmts(&mut self, stmts: &[Stmt], out: &mut String) -> Result<(), ZError> {
        for s in stmts {
            self.gen_stmt(s, out)?;
        }
        Ok(())
    }

    /// 在作用域栈中查找变量，返回 C 变量名；未找到返回 None
    fn lookup(&self, name: &str) -> Option<String> {
        for scope in self.scopes.iter().rev() {
            if let Some(v) = scope.get(name) {
                return Some(v.clone());
            }
        }
        None
    }

    /// 赋值：若变量已声明 → 释放旧值并重赋值；否则 → 在当前作用域声明新变量
    /// 返回生成的 C 文本（含尾换行）；临时变量名唯一（避免同作用域重定义）
    fn assign_var(&mut self, name: &str, value_expr: &str) -> String {
        if let Some(v) = self.lookup(name) {
            let t = self.temp();
            format!(
                "    HnValue _t{} = {};\n    hn_free_value({});\n    {} = _t{};\n",
                t, value_expr, v, v, t
            )
        } else {
            let v = format!("v{}", self.var_counter);
            self.var_counter += 1;
            self.scopes
                .last_mut()
                .expect("scope")
                .insert(name.to_string(), v.clone());
            format!("    HnValue {} = {};\n", v, value_expr)
        }
    }

    /// 生成一个语句
    fn gen_stmt(&mut self, s: &Stmt, out: &mut String) -> Result<(), ZError> {
        match s {
            Stmt::Assign { name, value, span } => {
                let e = self.gen_expr(value)?;
                out.push_str(&self.assign_var(name, &e));
                Ok(())
            }
            Stmt::VarDecl { name, ty, init, span } => {
                let e = match init {
                    Some(i) => self.gen_expr(i)?,
                    None => match ty {
                        TyName::Int => "hn_int(0)".to_string(),
                        TyName::Float => "hn_float(0.0)".to_string(),
                        TyName::Bool => "hn_bool(false)".to_string(),
                        TyName::Str => "hn_str(\"\")".to_string(),
                        TyName::Var(_) => "hn_null()".to_string(),
                    },
                };
                out.push_str(&self.assign_var(name, &e));
                Ok(())
            }
            Stmt::AssignOp { name, op, value, span } => {
                let v = self.lookup(name).ok_or_else(|| {
                    zerr(
                        &self.file,
                        &self.src,
                        codes::UNDEFINED,
                        format!("undefined variable `{}`", name),
                        *span,
                        Some("声明后再使用复合赋值"),
                    )
                })?;
                let rhs = self.gen_expr(value)?;
                let f = match op {
                    CompoundOp::Add => "hn_add_v",
                    CompoundOp::Sub => "hn_sub_v",
                    CompoundOp::Mul => "hn_mul_v",
                    CompoundOp::Div => "hn_div_v",
                    CompoundOp::Mod => "hn_mod_v",
                };
                let rt = self.temp();
                out.push_str(&format!(
                    "    HnValue _r{} = {}(hn_copy({}), {});\n    hn_free_value({});\n    {} = _r{};\n",
                    rt, f, v, rhs, v, v, rt
                ));
                Ok(())
            }
            Stmt::IndexAssign { target, value, span } => {
                // 索引赋值：克隆容器链并写回基变量（保持拷贝语义）
                self.gen_index_assign(target, value, out)
            }
            Stmt::DestructAssign { targets, value, span } => {
                let e = self.gen_expr(value)?;
                let t = self.temp();
                out.push_str(&format!("    HnValue _t{} = {};\n", t, e));
                for (i, (name, key)) in targets.iter().enumerate() {
                    let val = match key {
                        None => format!("hn_index_v(hn_copy(_t{}), hn_int({}))", t, i),
                        Some(k) => format!("hn_field_v(hn_copy(_t{}), {})", t, c_str_lit(k)),
                    };
                    out.push_str(&self.assign_var(name, &val));
                }
                out.push_str(&format!("    hn_free_value(_t{});\n", t));
                Ok(())
            }
            Stmt::Block { stmts, span } => {
                out.push_str("    {\n");
                self.scopes.push(HashMap::new());
                self.gen_stmts(stmts, out)?;
                self.scopes.pop();
                out.push_str("    }\n");
                Ok(())
            }
            Stmt::If { cond, then_branch, else_branch, span } => {
                let c = self.gen_expr(cond)?;
                out.push_str(&format!("    if (hn_truthy({})) {{\n", c));
                self.scopes.push(HashMap::new());
                self.gen_stmts(then_branch, out)?;
                self.scopes.pop();
                if let Some(eb) = else_branch {
                    out.push_str("    } else {\n");
                    self.scopes.push(HashMap::new());
                    self.gen_stmts(eb, out)?;
                    self.scopes.pop();
                }
                out.push_str("    }\n");
                Ok(())
            }
            Stmt::While { cond, body, span } => {
                let c = self.gen_expr(cond)?;
                let ls = format!("_ls{}", self.temp());
                out.push_str(&format!("    jmp_buf* {} = hn_jmp_top;\n", ls));
                out.push_str(&format!("    while (hn_truthy({})) {{\n", c));
                self.loop_saves.push(ls);
                self.cont_targets.push(None);
                self.scopes.push(HashMap::new());
                self.gen_stmts(body, out)?;
                self.scopes.pop();
                self.cont_targets.pop();
                self.loop_saves.pop();
                out.push_str("    }\n");
                Ok(())
            }
            Stmt::DoWhile { body, cond, span } => {
                let ls = format!("_ls{}", self.temp());
                out.push_str(&format!("    jmp_buf* {} = hn_jmp_top;\n", ls));
                out.push_str("    do {\n");
                self.loop_saves.push(ls);
                self.cont_targets.push(None);
                self.scopes.push(HashMap::new());
                self.gen_stmts(body, out)?;
                self.scopes.pop();
                self.cont_targets.pop();
                self.loop_saves.pop();
                let c = self.gen_expr(cond)?;
                out.push_str(&format!("    }} while (hn_truthy({}));\n", c));
                Ok(())
            }
            Stmt::ForC { init, cond, step, body, span } => {
                // init 在循环外执行一次；continue 需跳到 step 前（用 goto 标签）
                let ls = format!("_ls{}", self.temp());
                let cont_label = format!("hn_cont{}", self.temp());
                if let Some(i) = init {
                    self.gen_stmt(i, out)?;
                }
                out.push_str(&format!("    jmp_buf* {} = hn_jmp_top;\n", ls));
                out.push_str("    for (;;) {\n");
                if let Some(c) = cond {
                    let e = self.gen_expr(c)?;
                    out.push_str(&format!("        if (!hn_truthy({})) break;\n", e));
                }
                self.loop_saves.push(ls);
                self.cont_targets.push(Some(cont_label.clone()));
                self.scopes.push(HashMap::new());
                self.gen_stmts(body, out)?;
                self.scopes.pop();
                self.cont_targets.pop();
                self.loop_saves.pop();
                out.push_str(&format!("        {}: ;\n", cont_label));
                if let Some(st) = step {
                    self.gen_stmt(st, out)?;
                }
                out.push_str("    }\n");
                Ok(())
            }
            Stmt::ForIn { var, var2, iter, body, span } => {
                let it = self.gen_expr(iter)?;
                let itn = self.temp();
                out.push_str(&format!("    HnValue _it{} = {};\n", itn, it));
                let vv = format!("v{}", self.var_counter);
                self.var_counter += 1;
                let vv2 = format!("v{}", self.var_counter);
                self.var_counter += 1;
                // 列表分支
                out.push_str(&format!("    if (_it{}.type == HN_LIST) {{\n", itn));
                out.push_str(&format!("        HnList* _l = _it{}.as.list;\n", itn));
                out.push_str(&format!("        HnValue {} = hn_null();\n", vv));
                if var2.is_some() {
                    out.push_str(&format!("        HnValue {} = hn_null();\n", vv2));
                }
                out.push_str("        for (int _i = 0; _i < _l->len; _i++) {\n");
                out.push_str(&format!("            hn_free_value({});\n", vv));
                out.push_str(&format!("            {} = hn_copy(_l->items[_i]);\n", vv));
                self.scopes.push(HashMap::new());
                self.scopes.last_mut().expect("scope").insert(var.clone(), vv.clone());
                if let Some(v2) = var2 {
                    self.scopes.last_mut().expect("scope").insert(v2.clone(), vv2.clone());
                }
                self.gen_stmts(body, out)?;
                self.scopes.pop();
                out.push_str("        }\n");
                out.push_str(&format!("        hn_free_value({});\n", vv));
                if var2.is_some() {
                    out.push_str(&format!("        hn_free_value({});\n", vv2));
                }
                out.push_str(&format!("    }} else if (_it{}.type == HN_DICT) {{\n", itn));
                out.push_str(&format!("        HnDict* _d = _it{}.as.dict;\n", itn));
                out.push_str(&format!("        HnValue {} = hn_null();\n", vv));
                if var2.is_some() {
                    out.push_str(&format!("        HnValue {} = hn_null();\n", vv2));
                }
                out.push_str("        for (int _i = 0; _i < _d->len; _i++) {\n");
                out.push_str(&format!("            hn_free_value({});\n", vv));
                out.push_str(&format!("            {} = hn_str(_d->keys[_i]);\n", vv));
                if var2.is_some() {
                    out.push_str(&format!("            hn_free_value({});\n", vv2));
                    out.push_str(&format!("            {} = hn_copy(_d->vals[_i]);\n", vv2));
                }
                self.scopes.push(HashMap::new());
                self.scopes.last_mut().expect("scope").insert(var.clone(), vv.clone());
                if let Some(v2) = var2 {
                    self.scopes.last_mut().expect("scope").insert(v2.clone(), vv2.clone());
                }
                self.gen_stmts(body, out)?;
                self.scopes.pop();
                out.push_str("        }\n");
                out.push_str(&format!("        hn_free_value({});\n", vv));
                if var2.is_some() {
                    out.push_str(&format!("        hn_free_value({});\n", vv2));
                }
                out.push_str("    } else {\n");
                out.push_str("        hn_throw_value(hn_err_new(1, \"for-in requires a list or dict\"));\n");
                out.push_str("    }\n");
                out.push_str(&format!("    hn_free_value(_it{});\n", itn));
                Ok(())
            }
            Stmt::Return { values, span } => {
                // 先恢复 hn_jmp_top（若在 try 内，避免 jmp_buf 悬挂）
                if !self.try_saves.is_empty() {
                    let top = self.try_saves.last().expect("try");
                    out.push_str(&format!("    hn_jmp_top = {};\n", top));
                }
                if values.is_empty() {
                    out.push_str("    return hn_null();\n");
                } else if values.len() == 1 {
                    let e = self.gen_expr(&values[0])?;
                    out.push_str(&format!("    return {};\n", e));
                } else {
                    // 多返回值打包为列表
                    let lt = self.temp();
                    out.push_str(&format!("    HnValue _l{} = hn_list_new();\n", lt));
                    for v in values {
                        let e = self.gen_expr(v)?;
                        out.push_str(&format!("    hn_list_push(_l{}, {});\n", lt, e));
                    }
                    out.push_str(&format!("    return _l{};\n", lt));
                }
                Ok(())
            }
            Stmt::Break { span } => {
                // 跳出循环：若 try 在循环内，恢复循环入口的 hn_jmp_top
                if let Some(ls) = self.loop_saves.last() {
                    out.push_str(&format!("    hn_jmp_top = {};\n", ls));
                }
                out.push_str("    break;\n");
                Ok(())
            }
            Stmt::Continue { span } => {
                if let Some(ls) = self.loop_saves.last() {
                    out.push_str(&format!("    hn_jmp_top = {};\n", ls));
                }
                match self.cont_targets.last() {
                    Some(Some(label)) => {
                        out.push_str(&format!("    goto {};\n", label));
                    }
                    _ => out.push_str("    continue;\n"),
                }
                Ok(())
            }
            Stmt::DebugPrint { expr, span } => {
                let e = self.gen_expr(expr)?;
                out.push_str(&format!("    hn_free_value({});\n", e));
                Ok(())
            }
            Stmt::ExprStmt { expr, span } => {
                let e = self.gen_expr(expr)?;
                out.push_str(&format!("    hn_free_value({});\n", e));
                Ok(())
            }
            Stmt::Breakpoint { .. } => Ok(()),          // AOT 非调试模式忽略
            Stmt::Export { .. } => Ok(()),              // 仅 --dll 相关
            Stmt::FnDef { .. } => Ok(()),               // 已收集
            Stmt::StructDef { .. } => Ok(()),           // 已收集
            Stmt::ClassDef { .. } => Ok(()),            // 已收集
            Stmt::Use { .. } => Ok(()),                 // 命名空间声明，无运行语义
            Stmt::Alias { .. } => Ok(()),               // 已收集（调用时解析）
            Stmt::Import { name, url, span, .. } => Err(zerr(
                &self.file,
                &self.src,
                codes::NOT_IMPLEMENTED,
                format!("import 模块 `{}` 在 AOT 模式暂不支持", name),
                *span,
                Some("AOT 编译为单文件；请先手动下载模块并合并脚本，或用解释器运行"),
            )),
            Stmt::Load { path, span, .. } => Err(zerr(
                &self.file,
                &self.src,
                codes::NOT_IMPLEMENTED,
                format!("load 动态库 `{}` 在 AOT 模式暂不支持", path),
                *span,
                Some("AOT 模式不支持 FFI 动态库加载；请用解释器运行"),
            )),
            Stmt::Go { callee, span, .. } => Err(zerr(
                &self.file,
                &self.src,
                codes::NOT_IMPLEMENTED,
                format!("go 并发调用 `{}` 在 AOT 模式暂不支持", callee),
                *span,
                Some("AOT 模式为单线程；请用解释器运行并发脚本"),
            )),
            Stmt::Try { body, catch_var, handler, span } => {
                let saved = format!("_sv{}", self.temp());
                out.push_str("    {\n");
                out.push_str("        jmp_buf _jb;\n");
                out.push_str(&format!("        jmp_buf* {} = hn_jmp_top;\n", saved));
                out.push_str("        hn_jmp_top = &_jb;\n");
                out.push_str("        if (setjmp(_jb) == 0) {\n");
                self.try_saves.push(saved.clone());
                self.scopes.push(HashMap::new());
                self.gen_stmts(body, out)?;
                self.scopes.pop();
                self.try_saves.pop();
                out.push_str(&format!("            hn_jmp_top = {};\n", saved));
                out.push_str("        } else {\n");
                out.push_str(&format!("            hn_jmp_top = {};\n", saved));
                out.push_str("            HnValue _e = hn_copy(hn_err_val);\n");
                out.push_str("            hn_free_value(hn_err_val);\n");
                out.push_str("            hn_err_val = hn_null();\n");
                self.scopes.push(HashMap::new());
                self.scopes
                    .last_mut()
                    .expect("scope")
                    .insert(catch_var.clone(), "_e".to_string());
                self.gen_stmts(handler, out)?;
                self.scopes.pop();
                out.push_str("            hn_free_value(_e);\n");
                out.push_str("        }\n");
                out.push_str("    }\n");
                Ok(())
            }
            Stmt::Throw { value, span } => {
                let e = self.gen_expr(value)?;
                out.push_str(&format!("    hn_throw_expr({});\n", e));
                Ok(())
            }
        }
    }

    /// 按名字查找函数定义（支持 "类.方法" 全名）
    fn fn_lookup(&self, name: &str) -> Option<AotFn> {
        if let Some(f) = self.fns.get(name) {
            return Some(f.clone());
        }
        if let Some((cls, m)) = name.split_once('.') {
            if let Some(methods) = self.classes.get(cls) {
                for (mn, f) in methods {
                    if mn == m {
                        return Some(f.clone());
                    }
                }
            }
        }
        None
    }

    /// 索引赋值：target 为 a[i] 或 m[i][j] 链，值语义克隆写回基变量
    fn gen_index_assign(&mut self, target: &Expr, value: &Expr, out: &mut String) -> Result<(), ZError> {
        // 收集索引链：从基变量向外 [i0, i1, ...]，基变量为链底 Ident
        let mut indices: Vec<&Expr> = Vec::new(); // 从外到内
        let mut cur = target;
        let mut base_name: Option<String> = None;
        loop {
            match cur {
                Expr::Index { obj, index, .. } => {
                    indices.push(index);
                    cur = obj;
                }
                Expr::Ident { name, .. } => {
                    base_name = Some(name.clone());
                    break;
                }
                _ => {
                    return Err(zerr(
                        &self.file,
                        &self.src,
                        codes::TYPE_MISMATCH,
                        "无效的索引赋值目标".to_string(),
                        expr_span(target),
                        Some("目标需为 a[i] 或 m[i][j] 形式的索引链"),
                    ));
                }
            }
        }
        let name = base_name.ok_or_else(|| {
            zerr(
                &self.file,
                &self.src,
                codes::TYPE_MISMATCH,
                "无效的索引赋值目标".to_string(),
                expr_span(target),
                Some("目标需为 a[i] 或 m[i][j] 形式的索引链"),
            )
        })?;
        let v = self.lookup(&name).ok_or_else(|| {
            zerr(
                &self.file,
                &self.src,
                codes::UNDEFINED,
                format!("undefined variable `{}`", name),
                expr_span(target),
                Some("索引赋值目标需为已声明的变量"),
            )
        })?;
        let d = indices.len();
        // 索引与值各求值一次到临时变量
        let mut it: Vec<String> = Vec::new();
        for (k, idx) in indices.iter().enumerate() {
            let ie = self.gen_expr(idx)?;
            let t = format!("_ix{}_{}", k, self.temp());
            out.push_str(&format!("    HnValue {} = {};\n", t, ie));
            it.push(t);
        }
        let vt = self.temp();
        let ve = self.gen_expr(value)?;
        out.push_str(&format!("    HnValue _val{} = {};\n", vt, ve));
        let mut cur_expr = format!("_val{}", vt);
        // 从内到外构建：读路径容器 + set
        for k in (0..d).rev() {
            // 容器 = 基变量沿 indices[0..k] 的读取路径拷贝
            let container = if k == 0 {
                format!("hn_copy({})", v)
            } else {
                let mut e = format!("hn_copy({})", v);
                for j in 0..k {
                    e = format!("hn_index_v({}, hn_copy({}))", e, it[j]);
                }
                e
            };
            cur_expr = format!("hn_index_set({}, hn_copy({}), {})", container, it[k], cur_expr);
        }
        // 写回基变量
        let nt = self.temp();
        out.push_str(&format!("    HnValue _n{} = {};\n", nt, cur_expr));
        out.push_str(&format!("    hn_free_value({});\n", v));
        out.push_str(&format!("    {} = _n{};\n", v, nt));
        // 释放索引临时（经 hn_copy 传入消费，原件在此回收）
        for t in &it {
            out.push_str(&format!("    hn_free_value({});\n", t));
        }
        Ok(())
    }
}

/// C 字符串字面量转义（用于生成 hn_str("...")）；控制字符用三位八进制（避免 \x 吞掉后续十六进制位）
fn c_str_lit(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\{:03o}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// AOT 支持的核心内置函数集合（与 RUNTIME_C 的 hn_call_builtin 分发一致）
fn is_aot_builtin(name: &str) -> bool {
    matches!(
        name,
        "print"
            | "len"
            | "to_str"
            | "to_int"
            | "to_float"
            | "type_of"
            | "is_int"
            | "is_float"
            | "is_bool"
            | "is_str"
            | "is_list"
            | "is_dict"
            | "is_null"
            | "append"
            | "contains"
            | "index_of"
            | "keys"
            | "values"
            | "has_key"
            | "abs"
            | "max"
            | "min"
            | "str_contains"
            | "str_replace"
            | "str_trim"
            | "read_file"
            | "write_file"
            | "file_exists"
            | "read_bytes"
            | "write_bytes"
            | "input"
            | "read_int"
            | "read_float"
            | "assert"
            | "clone"
            | "copy"
            | "time.now"
            | "time.sleep"
            | "random.int"
            | "random.float"
    )
}

impl AotGen {
    /// 生成表达式：返回求值为 owned HnValue 的 C 表达式。
    /// 约定：二元/比较/索引等操作函数消费其参数（生成器直接嵌套，无需手动释放临时值）。
    fn gen_expr(&mut self, e: &Expr) -> Result<String, ZError> {
        match e {
            Expr::IntLit(v, _) => Ok(format!("hn_int({})", v)),
            Expr::FloatLit(v, _) => {
                let s = v.to_string();
                let lit = if s.contains('.') || s.contains('e') || s.contains('E') {
                    s
                } else {
                    format!("{}.0", s)
                };
                Ok(format!("hn_float({})", lit))
            }
            Expr::BoolLit(b, _) => Ok(if *b { "hn_bool(true)".to_string() } else { "hn_bool(false)".to_string() }),
            Expr::StrLit(s, _) => Ok(format!("hn_str({})", c_str_lit(s))),
            Expr::Ident { name, span } => {
                if let Some(v) = self.lookup(name) {
                    Ok(format!("hn_copy({})", v))
                } else {
                    // 可能是模块函数名被当作值使用（如 print）——解释器报 undefined variable
                    Err(zerr(
                        &self.file,
                        &self.src,
                        codes::UNDEFINED,
                        format!("undefined variable `{}`", name),
                        *span,
                        Some("声明后再读取变量"),
                    ))
                }
            }
            Expr::ListLit(items, _) => {
                let mut parts = Vec::new();
                for it in items {
                    parts.push(self.gen_expr(it)?);
                }
                let mut s = String::from("({ HnValue _l = hn_list_new();");
                for p in parts {
                    s.push_str(&format!(" hn_list_push(_l, {});", p));
                }
                s.push_str(" _l; })");
                Ok(s)
            }
            Expr::DictLit(entries, _) => {
                let mut s = String::from("({ HnValue _d = hn_dict_new();");
                for (k, v) in entries {
                    let ve = self.gen_expr(v)?;
                    s.push_str(&format!(" hn_dict_set(_d, {}, {});", c_str_lit(k), ve));
                }
                s.push_str(" _d; })");
                Ok(s)
            }
            Expr::ListComp { elem, var, var2, iter, cond, span } => {
                self.gen_comp(elem, None, var, var2, iter, cond, true, *span)
            }
            Expr::DictComp { key, value, var, var2, iter, cond, span } => {
                self.gen_comp(key, Some(value), var, var2, iter, cond, false, *span)
            }
            Expr::FStr(segs, _) => {
                // 逐段拼接：hn_add_v(hn_str(lit), hn_to_str_v(code)) 链式
                let mut parts: Vec<String> = Vec::new();
                for seg in segs {
                    match seg {
                        FStrSeg::Lit(s) => parts.push(format!("hn_str({})", c_str_lit(s))),
                        FStrSeg::Code(c) => {
                            let ce = self.gen_expr(c)?;
                            parts.push(format!("hn_to_str_v({})", ce));
                        }
                    }
                }
                if parts.is_empty() {
                    return Ok("hn_str(\"\")".to_string());
                }
                let mut s = parts[0].clone();
                for p in parts.iter().skip(1) {
                    s = format!("hn_add_v({}, {})", s, p);
                }
                Ok(s)
            }
            Expr::Field { obj, field, span } => {
                let o = self.gen_expr(obj)?;
                Ok(format!("hn_field_v({}, {})", o, c_str_lit(field)))
            }
            Expr::OptionalField { obj, field, span } => {
                let o = self.gen_expr(obj)?;
                Ok(format!(
                    "({{ HnValue _o = {}; HnValue _r; if (_o.type == HN_NULL) {{ _r = hn_null(); hn_free_value(_o); }} else {{ _r = hn_field_v(_o, {}); }} _r; }})",
                    o,
                    c_str_lit(field)
                ))
            }
            Expr::Index { obj, index, span } => {
                let o = self.gen_expr(obj)?;
                let i = self.gen_expr(index)?;
                Ok(format!("hn_index_v({}, {})", o, i))
            }
            Expr::Unary { op, expr, span } => {
                let x = self.gen_expr(expr)?;
                Ok(match op {
                    UnOp::Neg => format!("hn_neg_v({})", x),
                    UnOp::Not => format!("hn_not_v({})", x),
                })
            }
            Expr::Binary { op, lhs, rhs, span } => {
                let l = self.gen_expr(lhs)?;
                let r = self.gen_expr(rhs)?;
                Ok(match op {
                    BinOp::Add => format!("hn_add_v({}, {})", l, r),
                    BinOp::Sub => format!("hn_sub_v({}, {})", l, r),
                    BinOp::Mul => format!("hn_mul_v({}, {})", l, r),
                    BinOp::Div => format!("hn_div_v({}, {})", l, r),
                    BinOp::Mod => format!("hn_mod_v({}, {})", l, r),
                    BinOp::Eq => format!("hn_eq_v({}, {})", l, r),
                    BinOp::Ne => format!("hn_ne_v({}, {})", l, r),
                    BinOp::Lt => format!("hn_lt_v({}, {})", l, r),
                    BinOp::Le => format!("hn_le_v({}, {})", l, r),
                    BinOp::Gt => format!("hn_gt_v({}, {})", l, r),
                    BinOp::Ge => format!("hn_ge_v({}, {})", l, r),
                    // 短路：lhs 决定是否求值 rhs
                    BinOp::And => format!(
                        "({{ HnValue _l = {}; HnValue _r = hn_is_true(_l) ? {} : hn_bool(false); hn_free_value(_l); _r; }})",
                        l, r
                    ),
                    BinOp::Or => format!(
                        "({{ HnValue _l = {}; HnValue _r = hn_is_true(_l) ? hn_bool(true) : {}; hn_free_value(_l); _r; }})",
                        l, r
                    ),
                    BinOp::Coalesce => format!(
                        "({{\n  HnValue _l = {};\n  HnValue _r;\n  if (_l.type == HN_NULL) {{ _r = {}; }}\n  else {{ _r = _l; }}\n  _r;\n}})",
                        l, r
                    ),
                })
            }
            Expr::Call { callee, args, span } => self.gen_call(callee, args, *span),
            Expr::Match { value, arms, span } => {
                let v = self.gen_expr(value)?;
                let mut s = String::from("({ HnValue _m = ");
                s.push_str(&v);
                s.push_str("; HnValue _r;\n");
                // 模式比较链：模式 → 分支体（模式为 None 表示 _ 通配符，作默认）
                let mut done = false;
                let mut indent = String::from("  ");
                for (pat, body) in arms {
                    let be = self.gen_expr(body)?;
                    match pat {
                        Some(p) => {
                            let pe = self.gen_expr(p)?;
                            s.push_str(&format!("{}if (hn_eq_raw(_m, {})) {{ _r = {}; }}\n", indent, pe, be));
                        }
                        None => {
                            s.push_str(&format!("{}else {{ _r = {}; }}\n", indent, be));
                            done = true;
                        }
                    }
                }
                if !done {
                    s.push_str(&format!("{}else {{ _r = hn_null(); }}\n", indent));
                }
                s.push_str("  hn_free_value(_m); _r; })");
                Ok(s)
            }
            Expr::IncDec { op, prefix, name, span } => {
                let v = self.lookup(name).ok_or_else(|| {
                    zerr(
                        &self.file,
                        &self.src,
                        codes::UNDEFINED,
                        format!("undefined variable `{}`", name),
                        *span,
                        Some("声明后再自增/自减"),
                    )
                })?;
                let f = match op {
                    IncOp::Inc => "hn_add_v",
                    IncOp::Dec => "hn_sub_v",
                };
                if *prefix {
                    Ok(format!(
                        "({{\n  HnValue _n = {}(hn_copy({}), hn_int(1));\n  hn_free_value({});\n  {} = _n;\n  hn_copy({});\n}})",
                        f, v, v, v, v
                    ))
                } else {
                    Ok(format!(
                        "({{\n  HnValue _o = hn_copy({});\n  HnValue _n = {}(hn_copy({}), hn_int(1));\n  hn_free_value({});\n  {} = _n;\n  _o;\n}})",
                        v, f, v, v, v
                    ))
                }
            }
            Expr::Ternary { cond, then_expr, else_expr, span } => {
                let c = self.gen_expr(cond)?;
                let t = self.gen_expr(then_expr)?;
                let e2 = self.gen_expr(else_expr)?;
                Ok(format!(
                    "({{\n  HnValue _c = {};\n  HnValue _r = hn_is_true(_c) ? {} : {};\n  hn_free_value(_c);\n  _r;\n}})",
                    c, t, e2
                ))
            }
            Expr::Lambda { params, body, span } => self.gen_lambda(params, body, *span),
        }
    }

    /// 推导式生成：is_list=true 时输出列表（elem 为元素），否则输出字典（elem 为键、value 为值）
    #[allow(clippy::too_many_arguments)]
    fn gen_comp(
        &mut self,
        elem: &Expr,
        value: Option<&Expr>,
        var: &str,
        var2: &Option<String>,
        iter: &Expr,
        cond: &Option<Box<Expr>>,
        is_list: bool,
        span: Span,
    ) -> Result<String, ZError> {
        let it = self.gen_expr(iter)?;
        // 循环变量名（每次迭代重新赋值；continue 无泄漏）
        let vv = format!("v{}", self.var_counter);
        self.var_counter += 1;
        let vv2 = format!("v{}", self.var_counter);
        self.var_counter += 1;
        let out_name = if is_list { "_l" } else { "_d" };
        let new_out = if is_list { "hn_list_new()" } else { "hn_dict_new()" };
        let mut s = String::new();
        s.push_str(&format!("({{\n  HnValue {} = {};\n", out_name, new_out));
        s.push_str(&format!("  HnValue _it = {};\n", it));
        s.push_str(&format!("  HnValue {} = hn_null();\n", vv));
        if var2.is_some() {
            s.push_str(&format!("  HnValue {} = hn_null();\n", vv2));
        }
        s.push_str("  if (_it.type == HN_LIST) {\n");
        s.push_str("    for (int _i = 0; _i < _it.as.list->len; _i++) {\n");
        s.push_str(&format!("      hn_free_value({});\n", vv));
        s.push_str(&format!("      {} = hn_copy(_it.as.list->items[_i]);\n", vv));
        self.scopes.push(HashMap::new());
        self.scopes.last_mut().expect("scope").insert(var.to_string(), vv.clone());
        if let Some(v2) = var2 {
            self.scopes.last_mut().expect("scope").insert(v2.clone(), vv2.clone());
        }
        let elem_c = self.gen_expr(elem)?;
        let val_c = match value {
            Some(v) => self.gen_expr(v)?,
            None => String::new(),
        };
        let cond_c = match cond {
            Some(c) => {
                let ce = self.gen_expr(c)?;
                format!("if (hn_truthy({})) ", ce)
            }
            None => String::new(),
        };
        if is_list {
            s.push_str(&format!("      {}hn_list_push(_l, {});\n", cond_c, elem_c));
        } else {
            s.push_str(&format!("      {}hn_dict_set_v(_d, {}, {});\n", cond_c, elem_c, val_c));
        }
        self.scopes.pop();
        s.push_str("    }\n");
        s.push_str("  } else if (_it.type == HN_DICT) {\n");
        s.push_str("    for (int _i = 0; _i < _it.as.dict->len; _i++) {\n");
        s.push_str(&format!("      hn_free_value({});\n", vv));
        s.push_str(&format!("      {} = hn_str(_it.as.dict->keys[_i]);\n", vv));
        if var2.is_some() {
            s.push_str(&format!("      hn_free_value({});\n", vv2));
            s.push_str(&format!("      {} = hn_copy(_it.as.dict->vals[_i]);\n", vv2));
        }
        self.scopes.push(HashMap::new());
        self.scopes.last_mut().expect("scope").insert(var.to_string(), vv.clone());
        if let Some(v2) = var2 {
            self.scopes.last_mut().expect("scope").insert(v2.clone(), vv2.clone());
        }
        let elem_d = self.gen_expr(elem)?;
        let val_d = match value {
            Some(v) => self.gen_expr(v)?,
            None => String::new(),
        };
        let cond_d = match cond {
            Some(c) => {
                let ce = self.gen_expr(c)?;
                format!("if (hn_truthy({})) ", ce)
            }
            None => String::new(),
        };
        if is_list {
            s.push_str(&format!("      {}hn_list_push(_l, {});\n", cond_d, elem_d));
        } else {
            s.push_str(&format!("      {}hn_dict_set_v(_d, {}, {});\n", cond_d, elem_d, val_d));
        }
        self.scopes.pop();
        s.push_str("    }\n");
        s.push_str("  }\n");
        s.push_str(&format!("  hn_free_value({}); hn_free_value(_it);\n", vv));
        if var2.is_some() {
            s.push_str(&format!("  hn_free_value({});\n", vv2));
        }
        s.push_str(&format!("  {};\n}})", out_name));
        Ok(s)
    }

    /// 函数调用：解析 callee（变量 lambda → 用户函数/类方法 → 结构体构造 → 内置）
    fn gen_call(&mut self, callee: &str, args: &[Expr], span: Span) -> Result<String, ZError> {
        // 先求值参数（自左向右，先入临时数组）
        let mut arg_exprs: Vec<String> = Vec::new();
        for a in args {
            arg_exprs.push(self.gen_expr(a)?);
        }
        let n = arg_exprs.len();

        // 1) 变量名 → lambda 调用
        if let Some(v) = self.lookup(callee) {
            let mut s = String::from("({ ");
            s.push_str(&format!("HnValue _a[{}] = {{ {} }}; ", n, arg_exprs.join(", ")));
            s.push_str(&format!("HnValue _r = hn_call_fn(hn_copy({}), _a, {}); ", v, n));
            for i in 0..n {
                s.push_str(&format!("hn_free_value(_a[{}]); ", i));
            }
            s.push_str("_r; })");
            return Ok(s);
        }

        // 2) 用户函数 / 类方法（"类.方法"）
        if self.fn_lookup(callee).is_some() {
            let slot = self.slot_for(callee);
            let mut s = String::from("({ ");
            s.push_str(&format!("HnValue _a[{}] = {{ {} }}; ", n, arg_exprs.join(", ")));
            s.push_str(&format!("HnValue _r = hn_f{}(_a, {}, NULL, 0); ", slot, n));
            for i in 0..n {
                s.push_str(&format!("hn_free_value(_a[{}]); ", i));
            }
            s.push_str("_r; })");
            return Ok(s);
        }

        // 3) 结构体构造：Name(字段...) → dict
        if let Some(fields) = self.structs.get(callee).cloned() {
            if fields.len() != n {
                return Err(zerr(
                    &self.file,
                    &self.src,
                    codes::ARG_COUNT,
                    format!("结构体 `{}` 需要 {} 个字段，实际传入 {}", callee, fields.len(), n),
                    span,
                    Some("按结构体字段顺序传参"),
                ));
            }
            let mut s = String::from("({ HnValue _d = hn_dict_new();");
            for (i, f) in fields.iter().enumerate() {
                s.push_str(&format!(" hn_dict_set(_d, {}, {});", c_str_lit(f), arg_exprs[i]));
            }
            s.push_str(" _d; })");
            return Ok(s);
        }

        // 4) 内置函数
        if is_aot_builtin(callee) {
            let mut s = String::from("({ ");
            s.push_str(&format!("HnValue _a[{}] = {{ {} }}; ", n, arg_exprs.join(", ")));
            s.push_str(&format!("HnValue _r = hn_call_builtin({}, _a, {}); ", c_str_lit(callee), n));
            for i in 0..n {
                s.push_str(&format!("hn_free_value(_a[{}]); ", i));
            }
            s.push_str("_r; })");
            return Ok(s);
        }

        Err(zerr(
            &self.file,
            &self.src,
            codes::NOT_IMPLEMENTED,
            format!("函数/内置 `{}` 在 AOT 模式暂不支持（未定义或超出核心内置集）", callee),
            span,
            Some("AOT 模式仅支持核心内置；重内置请用解释器运行"),
        ))
    }

    /// lambda 生成：创建闭包值（捕获当前可见变量），并生成 hn_lm<k> 函数
    fn gen_lambda(&mut self, params: &[Param], body: &[Stmt], span: Span) -> Result<String, ZError> {
        let k = self.lambda_counter;
        self.lambda_counter += 1;
        // 捕获列表：当前作用域栈全部可见变量（外→内，内层覆盖外层，去重）
        let mut captured: Vec<(String, String)> = Vec::new(); // (变量名, 闭包内 C 名)
        let mut seen: HashSet<String> = HashSet::new();
        for scope in &self.scopes {
            let mut names: Vec<&String> = scope.keys().collect();
            names.sort();
            for name in names {
                if seen.insert(name.clone()) {
                    captured.push((name.clone(), format!("_c{}", captured.len())));
                }
            }
        }
        // 生成 lambda 函数体（独立作用域：捕获变量 → _cN，参数 → vN）
        let saved_scopes = self.scopes.clone();
        let saved_vc = self.var_counter;
        let saved_tc = self.temp_counter;
        self.scopes.clear();
        self.scopes.push(HashMap::new());
        for (name, cname) in &captured {
            self.scopes
                .last_mut()
                .expect("scope")
                .insert(name.clone(), cname.clone());
        }
        let mut body_c = String::new();
        // 捕获变量副本（每次调用独立，赋值不影响外部——与解释器一致）；先于参数声明（默认值表达式可引用捕获变量）
        for (i, (_, cname)) in captured.iter().enumerate() {
            body_c.push_str(&format!("    HnValue {} = hn_copy(cap[{}]);\n", cname, i));
        }
        for (i, p) in params.iter().enumerate() {
            let vname = format!("v{}", self.var_counter);
            self.var_counter += 1;
            self.scopes
                .last_mut()
                .expect("scope")
                .insert(p.name.clone(), vname.clone());
            let init = match &p.default {
                Some(d) => {
                    let de = self.gen_expr(d)?;
                    format!("(nargs > {} ? hn_copy(args[{}]) : {})", i, i, de)
                }
                None => format!("(nargs > {} ? hn_copy(args[{}]) : hn_null())", i, i),
            };
            body_c.push_str(&format!("    HnValue {} = {};\n", vname, init));
        }
        self.gen_stmts(body, &mut body_c)?;
        body_c.push_str("    return hn_null();\n");
        self.scopes = saved_scopes;
        self.var_counter = saved_vc;
        self.temp_counter = saved_tc;
        // 组装 hn_lm<k>
        let mut text = String::new();
        text.push_str(&format!("static HnValue hn_lm{}(HnValue* args, int nargs, HnValue* cap, int ncap) {{\n", k));
        text.push_str("    (void)ncap;\n");
        text.push_str(&body_c);
        text.push_str("}\n");
        self.lambda_out.push_str(&text);
        // 创建闭包：hn_fn_new(hn_lm<k>, cap 数组, K)
        if captured.is_empty() {
            Ok(format!("hn_fn_new(hn_lm{}, NULL, 0)", k))
        } else {
            let mut s = String::from("({ ");
            s.push_str(&format!("HnValue _cap[{}] = {{ ", captured.len()));
            let mut first = true;
            for (name, _) in &captured {
                let src = self.lookup(name).unwrap_or_else(|| "hn_null()".to_string());
                if !first {
                    s.push_str(", ");
                }
                s.push_str(&format!("hn_copy({})", src));
                first = false;
            }
            s.push_str(&format!(" }}; hn_fn_new(hn_lm{}, _cap, {}); }})", k, captured.len()));
            Ok(s)
        }
    }
}

